import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const beaverCreek: Resort = {
  id: 'resort:beaver-creek',
  slug: 'beaver-creek',
  name: 'Beaver Creek Resort',
  tagline: 'World-class luxury with impeccable service',
  description: 'Beaver Creek Resort defines luxury skiing in Colorado, with world-class grooming, an elegant alpine village, and legendary après-ski cookies. The resort offers impeccable service and varied terrain from the gentle slopes of Bachelor Gulch to the challenging Birds of Prey World Cup downhill course. Beaver Creek\'s exclusive atmosphere and consistent quality have made it a favorite among discerning skiers.',
  isActive: true,
  isLost: false,
  location: { lat: 39.6042, lng: -106.5167 },
  nearestCity: 'Avon, CO',
  distanceFromDenver: 107,
  driveTimeFromDenver: 130,
  stats: {
    skiableAcres: 1832,
    liftsCount: 24,
    runsCount: 150,
    verticalDrop: 3340,
    baseElevation: 8100,
    summitElevation: 11440,
    avgAnnualSnowfall: 325,
  },
  terrain: {
    beginner: 19,
    intermediate: 43,
    advanced: 20,
    expert: 18,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['epic'],
  rating: 4.7,
  reviewCount: 1567,
  heroImage: '/images/beaver-creek-hero.jpg',
  websiteUrl: 'https://www.beavercreek.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: true,
  },
  tags: ['destination', 'epic-pass', 'luxury', 'world-cup', 'colorado', 'groomed'],
};
