import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const breckenridge: Resort = {
  id: 'resort:breckenridge',
  slug: 'breckenridge',
  name: 'Breckenridge Ski Resort',
  tagline: 'Five peaks of terrain above a historic mining town',
  description: 'Breckenridge is Colorado\'s most popular ski destination, combining five interconnected peaks with one of Colorado\'s most charming historic Main Streets. The resort spans from gentle beginner terrain to the highest lift-served terrain in North America on Peak 8. The Victorian mining town below offers hundreds of restaurants and shops in beautifully preserved buildings, creating a complete mountain vacation experience.',
  isActive: true,
  isLost: false,
  location: { lat: 39.4817, lng: -106.0384 },
  nearestCity: 'Breckenridge, CO',
  distanceFromDenver: 85,
  driveTimeFromDenver: 105,
  stats: {
    skiableAcres: 2908,
    liftsCount: 35,
    runsCount: 187,
    verticalDrop: 3398,
    baseElevation: 9600,
    summitElevation: 12998,
    avgAnnualSnowfall: 353,
  },
  terrain: {
    beginner: 14,
    intermediate: 31,
    advanced: 36,
    expert: 19,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['epic'],
  rating: 4.6,
  reviewCount: 2456,
  heroImage: '/images/breckenridge-hero.jpg',
  websiteUrl: 'https://www.breckenridge.com',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: true,
  },
  tags: ['destination', 'epic-pass', 'popular', 'historic-town', 'colorado', 'five-peaks'],
};
