import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const fernie: Resort = {
  id: 'resort:fernie',
  slug: 'fernie',
  name: 'Fernie Alpine Resort',
  tagline: 'Legendary powder in the heart of the Canadian Rockies',
  description: 'Fernie Alpine Resort is a powder skier\'s paradise, receiving an average of 37 feet of snow annually in the Lizard Range of the Canadian Rockies. The resort spans five alpine bowls with terrain ranging from gentle groomers to extreme chutes and legendary tree skiing. Fernie maintains a laid-back, locals-first atmosphere that draws dedicated skiers from around the world seeking fresh tracks without the crowds. The historic coal mining town of Fernie provides an authentic mountain community experience with excellent restaurants and a welcoming vibe.',
  isActive: true,
  isLost: false,
  location: { lat: 49.4626, lng: -115.0871 },
  nearestCity: 'Fernie, BC',
  distanceFromDenver: 720,
  driveTimeFromDenver: 660,
  stats: {
    skiableAcres: 2504,
    liftsCount: 10,
    runsCount: 142,
    verticalDrop: 2816,
    baseElevation: 3550,
    summitElevation: 6316,
    avgAnnualSnowfall: 444,
  },
  terrain: {
    beginner: 30,
    intermediate: 40,
    advanced: 30,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.6,
  reviewCount: 876,
  heroImage: '/images/fernie-hero.jpg',
  websiteUrl: 'https://www.skifernie.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/skifernie',
    instagram: 'https://www.instagram.com/skifernie',
  },
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['powder', 'ikon-pass', 'bowls', 'local', 'british-columbia', 'authentic'],
  highSpeedLifts: {
    count: 4,
    items: [
      { name: 'Timber Bowl Express', url: 'https://www.skifernie.com' },
      { name: 'White Pass Quad', url: 'https://www.skifernie.com' },
      { name: 'Great Bear Express', url: 'https://www.skifernie.com' },
      { name: 'Elk Quad', url: 'https://www.skifernie.com' },
    ],
  },
};
