import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const birchHill: Resort = {
  id: 'resort:birch-hill',
  slug: 'birch-hill',
  name: 'Birch Hill Ski Area',
  tagline: 'Former Fairbanks area ski hill',
  description: 'Birch Hill Ski Area was a small community ski area that served the Fairbanks area in Interior Alaska. The area provided local families with accessible skiing before operations ceased. The site now focuses on cross-country skiing and other winter recreation activities.',
  isActive: false,
  isLost: true,
  location: { lat: 64.8700, lng: -147.6800 },
  nearestCity: 'Fairbanks, AK',
  distanceFromDenver: 3050,
  driveTimeFromDenver: 2900,
  stats: {
    skiableAcres: 20,
    liftsCount: 1,
    runsCount: 5,
    verticalDrop: 250,
    baseElevation: 500,
    summitElevation: 750,
    avgAnnualSnowfall: 60,
  },
  terrain: {
    beginner: 50,
    intermediate: 40,
    advanced: 10,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 0,
  reviewCount: 0,
  heroImage: '/images/birch-hill-hero.jpg',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['defunct', 'community', 'alaska', 'historic'],
};
