import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const eaglecrest: Resort = {
  id: 'resort:eaglecrest',
  slug: 'eaglecrest',
  name: 'Eaglecrest Ski Area',
  tagline: 'Community-owned skiing in Alaska\'s capital',
  description: 'Eaglecrest Ski Area is a municipally-owned ski area located on Douglas Island, just 12 miles from downtown Juneau, Alaska\'s capital city. As one of the few community-owned ski areas in the United States, Eaglecrest offers affordable skiing with a local, uncrowded atmosphere. The area receives substantial snowfall from Pacific storms and features varied terrain suitable for all ability levels. With no lift lines and genuine Alaska wilderness surroundings, Eaglecrest provides an authentic, no-frills skiing experience.',
  isActive: true,
  isLost: false,
  location: { lat: 58.3042, lng: -134.5139 },
  nearestCity: 'Juneau, AK',
  distanceFromDenver: 2400,
  driveTimeFromDenver: 2400,
  stats: {
    skiableAcres: 640,
    liftsCount: 4,
    runsCount: 36,
    verticalDrop: 1540,
    baseElevation: 1200,
    summitElevation: 2740,
    avgAnnualSnowfall: 400,
  },
  terrain: {
    beginner: 20,
    intermediate: 40,
    advanced: 25,
    expert: 15,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['indy'],
  rating: 4.3,
  reviewCount: 256,
  heroImage: '/images/eaglecrest-hero.jpg',
  websiteUrl: 'https://www.skijuneau.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['local', 'indy-pass', 'uncrowded', 'community-owned', 'alaska', 'affordable'],
};
