import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const hilltop: Resort = {
  id: 'resort:hilltop',
  slug: 'hilltop',
  name: 'Hilltop Ski Area',
  tagline: 'Anchorage\'s backyard ski hill with city lights skiing',
  description: 'Hilltop Ski Area is Anchorage\'s hometown ski hill, located just minutes from downtown within the city limits. This small but beloved area offers night skiing with views of the Anchorage skyline and Cook Inlet, providing a uniquely urban Alaska skiing experience. Hilltop serves as the training ground for many of Alaska\'s competitive skiers and is perfect for families and beginners looking for an accessible introduction to skiing.',
  isActive: true,
  isLost: false,
  location: { lat: 61.1389, lng: -149.7308 },
  nearestCity: 'Anchorage, AK',
  distanceFromDenver: 2750,
  driveTimeFromDenver: 2600,
  stats: {
    skiableAcres: 30,
    liftsCount: 2,
    runsCount: 12,
    verticalDrop: 294,
    baseElevation: 1150,
    summitElevation: 1444,
    avgAnnualSnowfall: 70,
  },
  terrain: {
    beginner: 40,
    intermediate: 40,
    advanced: 20,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.8,
  reviewCount: 156,
  heroImage: '/images/hilltop-hero.jpg',
  websiteUrl: 'https://www.hilltopskiarea.org',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['local', 'beginner-friendly', 'night-skiing', 'urban', 'alaska', 'family'],
};
