import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const majesticValley: Resort = {
  id: 'resort:majestic-valley',
  slug: 'majestic-valley',
  name: 'Majestic Valley',
  tagline: 'Former wilderness ski area in remote Alaska',
  description: 'Majestic Valley was a remote ski operation in the Alaska wilderness that offered a unique backcountry skiing experience. The area operated on a limited basis, providing access to untouched powder in a spectacular mountain setting. Operational challenges and remoteness eventually led to its closure.',
  isActive: false,
  isLost: true,
  location: { lat: 61.5000, lng: -149.0000 },
  nearestCity: 'Anchorage, AK',
  distanceFromDenver: 2800,
  driveTimeFromDenver: 2650,
  stats: {
    skiableAcres: 100,
    liftsCount: 1,
    runsCount: 10,
    verticalDrop: 1200,
    baseElevation: 1500,
    summitElevation: 2700,
    avgAnnualSnowfall: 200,
  },
  terrain: {
    beginner: 10,
    intermediate: 40,
    advanced: 35,
    expert: 15,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 0,
  reviewCount: 0,
  heroImage: '/images/majestic-valley-hero.jpg',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['defunct', 'remote', 'alaska', 'wilderness', 'backcountry'],
};
