import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mooseMountain: Resort = {
  id: 'resort:moose-mountain',
  slug: 'moose-mountain',
  name: 'Moose Mountain Ski Area',
  tagline: 'Family skiing in the Matanuska-Susitna Valley',
  description: 'Moose Mountain Ski Area serves the Matanuska-Susitna Valley community north of Anchorage, providing accessible family skiing in a friendly, low-key environment. The area offers gentle terrain ideal for beginners and families, with affordable lift tickets and a welcoming atmosphere. Moose Mountain focuses on providing a quality experience for developing skiers and snowboarders.',
  isActive: true,
  isLost: false,
  location: { lat: 61.7253, lng: -149.2697 },
  nearestCity: 'Palmer, AK',
  distanceFromDenver: 2780,
  driveTimeFromDenver: 2630,
  stats: {
    skiableAcres: 25,
    liftsCount: 1,
    runsCount: 8,
    verticalDrop: 350,
    baseElevation: 800,
    summitElevation: 1150,
    avgAnnualSnowfall: 90,
  },
  terrain: {
    beginner: 50,
    intermediate: 35,
    advanced: 15,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.7,
  reviewCount: 67,
  heroImage: '/images/moose-mountain-hero.jpg',
  websiteUrl: 'https://www.moosemountainskiarea.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['local', 'beginner-friendly', 'family', 'alaska', 'affordable'],
};
