import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mtEyak: Resort = {
  id: 'resort:mt-eyak',
  slug: 'mt-eyak',
  name: 'Mt. Eyak',
  tagline: 'Historic single-chair skiing in coastal Cordova',
  description: 'Mt. Eyak Ski Area in Cordova, Alaska is home to one of the oldest operating single chairlifts in North America, a 1939 model that provides a uniquely nostalgic experience. Accessible only by air or sea (Cordova has no road connection to the rest of Alaska), Mt. Eyak offers a truly remote skiing experience with spectacular views of Prince William Sound. The area is community-operated and maintains a laid-back, authentic Alaska atmosphere.',
  isActive: true,
  isLost: false,
  location: { lat: 60.5417, lng: -145.7575 },
  nearestCity: 'Cordova, AK',
  distanceFromDenver: 2900,
  driveTimeFromDenver: 2800,
  stats: {
    skiableAcres: 45,
    liftsCount: 1,
    runsCount: 10,
    verticalDrop: 800,
    baseElevation: 100,
    summitElevation: 900,
    avgAnnualSnowfall: 200,
  },
  terrain: {
    beginner: 30,
    intermediate: 40,
    advanced: 30,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.2,
  reviewCount: 45,
  heroImage: '/images/mt-eyak-hero.jpg',
  websiteUrl: 'https://www.mteyak.org',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['historic', 'remote', 'single-chair', 'alaska', 'coastal'],
};
