import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const cloudmont: Resort = {
  id: 'resort:cloudmont',
  slug: 'cloudmont',
  name: 'Cloudmont Ski and Golf Resort',
  tagline: 'The southernmost ski resort in the United States',
  description: 'Cloudmont Ski and Golf Resort holds the distinction of being the southernmost ski resort in the United States, located atop Lookout Mountain in Mentone, Alabama. This small family-friendly resort offers a unique skiing experience in the Deep South, with snowmaking capabilities that allow for a reliable season despite the southern latitude. The resort features gentle terrain perfect for beginners and families looking for an accessible introduction to skiing without traveling to distant mountain ranges.',
  isActive: true,
  isLost: false,
  location: { lat: 34.5672, lng: -85.5847 },
  nearestCity: 'Mentone, AL',
  distanceFromDenver: 1250,
  driveTimeFromDenver: 1080,
  stats: {
    skiableAcres: 12,
    liftsCount: 2,
    runsCount: 4,
    verticalDrop: 150,
    baseElevation: 1650,
    summitElevation: 1800,
    avgAnnualSnowfall: 2,
  },
  terrain: {
    beginner: 60,
    intermediate: 30,
    advanced: 10,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.5,
  reviewCount: 124,
  heroImage: '/images/cloudmont-hero.jpg',
  websiteUrl: 'https://www.cloudmont.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['beginner-friendly', 'family', 'southern', 'small', 'night-skiing'],
};
