import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const bigWhite: Resort = {
  id: 'resort:big-white',
  slug: 'big-white',
  name: 'Big White Ski Resort',
  tagline: 'Ski in, ski out with champagne powder and snow ghosts',
  description: 'Big White Ski Resort is Canada\'s largest fully ski-in, ski-out resort, with all accommodations providing direct slope access. Located in British Columbia\'s Okanagan region, Big White is famous for its champagne powder and the iconic "snow ghosts" - trees covered in snow and rime ice that create an otherworldly landscape. The resort offers a wide variety of terrain across 2,765 acres, from gentle beginner runs to challenging glades and bowls. The family-friendly village atmosphere and reliable snow conditions make Big White a favorite for families and powder seekers alike.',
  isActive: true,
  isLost: false,
  location: { lat: 49.7263, lng: -118.9366 },
  nearestCity: 'Kelowna, BC',
  distanceFromDenver: 780,
  driveTimeFromDenver: 720,
  stats: {
    skiableAcres: 2765,
    liftsCount: 16,
    runsCount: 119,
    verticalDrop: 2550,
    baseElevation: 5760,
    summitElevation: 7606,
    avgAnnualSnowfall: 295,
  },
  terrain: {
    beginner: 18,
    intermediate: 56,
    advanced: 18,
    expert: 8,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.5,
  reviewCount: 1123,
  heroImage: '/images/big-white-hero.jpg',
  websiteUrl: 'https://www.bigwhite.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/bigwhiteskiresort',
    instagram: 'https://www.instagram.com/bigwhite',
  },
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: true,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'ski-in-ski-out', 'family', 'british-columbia', 'snow-ghosts'],
  highSpeedLifts: {
    count: 4,
    items: [
      { name: 'Bullet Express', url: 'https://www.bigwhite.com' },
      { name: 'Falcon Chair', url: 'https://www.bigwhite.com' },
      { name: 'Gem Lake Express', url: 'https://www.bigwhite.com' },
      { name: 'Alpine T-Bar', url: 'https://www.bigwhite.com' },
    ],
  },
};
