import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mountLemmon: Resort = {
  id: 'resort:mount-lemmon',
  slug: 'mount-lemmon',
  name: 'Mount Lemmon Ski Valley',
  tagline: 'The southernmost ski area in the United States',
  description: 'Mount Lemmon Ski Valley holds the distinction of being the southernmost ski area in the United States, located in the Santa Catalina Mountains just north of Tucson, Arizona. This small community ski area offers a remarkable contrast - skiing within an hour\'s drive of the Sonoran Desert. The resort operates primarily on snowmaking and offers a friendly, low-key atmosphere perfect for beginners and families. Rising from the desert floor, the Catalina Highway provides one of the most dramatic drives to any ski area in America.',
  isActive: true,
  isLost: false,
  location: { lat: 32.4428, lng: -110.7886 },
  nearestCity: 'Tucson, AZ',
  distanceFromDenver: 640,
  driveTimeFromDenver: 600,
  stats: {
    skiableAcres: 200,
    liftsCount: 3,
    runsCount: 22,
    verticalDrop: 950,
    baseElevation: 8200,
    summitElevation: 9150,
    avgAnnualSnowfall: 180,
  },
  terrain: {
    beginner: 30,
    intermediate: 50,
    advanced: 15,
    expert: 5,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.8,
  reviewCount: 289,
  heroImage: '/images/mount-lemmon-hero.jpg',
  websiteUrl: 'https://www.skithelemmon.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['small', 'beginner-friendly', 'family', 'southern', 'arizona', 'desert-skiing'],
};
