import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const sunrisePark: Resort = {
  id: 'resort:sunrise-park',
  slug: 'sunrise-park',
  name: 'Sunrise Park Resort',
  tagline: 'Arizona\'s largest ski area on the White Mountain Apache Reservation',
  description: 'Sunrise Park Resort is Arizona\'s largest ski destination, owned and operated by the White Mountain Apache Tribe. Located in the scenic White Mountains of eastern Arizona, the resort spans three interconnected mountains offering diverse terrain for all skill levels. The area benefits from higher elevation and more consistent snowfall than other Arizona resorts, with extensive snowmaking to supplement natural conditions. The resort offers a family-friendly atmosphere with affordable lift tickets and a genuine Southwestern character.',
  isActive: true,
  isLost: false,
  location: { lat: 33.9708, lng: -109.5678 },
  nearestCity: 'Greer, AZ',
  distanceFromDenver: 580,
  driveTimeFromDenver: 540,
  stats: {
    skiableAcres: 800,
    liftsCount: 8,
    runsCount: 65,
    verticalDrop: 1800,
    baseElevation: 9200,
    summitElevation: 11000,
    avgAnnualSnowfall: 250,
  },
  terrain: {
    beginner: 30,
    intermediate: 40,
    advanced: 20,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 412,
  heroImage: '/images/sunrise-park-hero.jpg',
  websiteUrl: 'https://www.sunriseskiparkaz.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['family', 'affordable', 'native-american-owned', 'arizona', 'three-mountains'],
};
