import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mtRose: Resort = {
  id: 'resort:mt-rose',
  slug: 'mt-rose',
  name: 'Mt. Rose Ski Tahoe',
  tagline: 'Lake Tahoe\'s highest base elevation and closest to Reno',
  description: 'Mt. Rose Ski Tahoe boasts the highest base elevation at Lake Tahoe at 8,260 feet, ensuring reliable snow conditions throughout the season. Located just 25 minutes from Reno, Mt. Rose is the most accessible Tahoe resort for Northern Nevada residents. The Chutes, a 1,500-acre expansion of expert terrain, added serious skiing to complement the resort\'s family-friendly reputation.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3147, lng: -119.8853 },
  nearestCity: 'Reno, NV',
  distanceFromDenver: 880,
  driveTimeFromDenver: 810,
  stats: {
    skiableAcres: 1200,
    liftsCount: 8,
    runsCount: 61,
    verticalDrop: 1800,
    baseElevation: 8260,
    summitElevation: 9700,
    avgAnnualSnowfall: 350,
  },
  terrain: {
    beginner: 20,
    intermediate: 30,
    advanced: 40,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.3,
  reviewCount: 567,
  heroImage: '/images/mt-rose-hero.jpg',
  websiteUrl: 'https://www.skirose.com',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'high-elevation', 'lake-tahoe', 'nevada', 'chutes'],
};
