import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const bearMountainCa: Resort = {
  id: 'resort:bear-mountain-ca',
  slug: 'bear-mountain-ca',
  name: 'Bear Mountain',
  tagline: 'Southern California\'s terrain park destination',
  description: 'Bear Mountain in Big Bear Lake is Southern California\'s premier destination for terrain parks and freestyle skiing. The resort is renowned for its extensive park setup, featuring multiple terrain parks, over 80 features, and two halfpipes that attract professional athletes and park enthusiasts from across the region. Connected to Snow Summit, Bear Mountain focuses on the freestyle experience while offering something for all ability levels.',
  isActive: true,
  isLost: false,
  location: { lat: 34.2272, lng: -116.8606 },
  nearestCity: 'Big Bear Lake, CA',
  distanceFromDenver: 760,
  driveTimeFromDenver: 700,
  stats: {
    skiableAcres: 198,
    liftsCount: 12,
    runsCount: 32,
    verticalDrop: 1665,
    baseElevation: 7140,
    summitElevation: 8805,
    avgAnnualSnowfall: 100,
  },
  terrain: {
    beginner: 15,
    intermediate: 55,
    advanced: 20,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.2,
  reviewCount: 678,
  heroImage: '/images/bear-mountain-ca-hero.jpg',
  websiteUrl: 'https://www.bigbearmountainresort.com/bear-mountain',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'terrain-parks', 'freestyle', 'california', 'big-bear'],
};
