import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const bearValley: Resort = {
  id: 'resort:bear-valley',
  slug: 'bear-valley',
  name: 'Bear Valley',
  tagline: 'Central Sierra\'s hidden powder stash',
  description: 'Bear Valley is a hidden gem in the Central Sierra Nevada, receiving some of the heaviest snowfall in California. Located on Highway 4 east of Arnold, Bear Valley offers uncrowded slopes, excellent tree skiing, and a friendly atmosphere that harks back to skiing\'s golden era. The resort\'s high base elevation and position in the storm track deliver reliable powder conditions throughout the season.',
  isActive: true,
  isLost: false,
  location: { lat: 38.4594, lng: -120.0417 },
  nearestCity: 'Bear Valley, CA',
  distanceFromDenver: 870,
  driveTimeFromDenver: 800,
  stats: {
    skiableAcres: 1680,
    liftsCount: 10,
    runsCount: 75,
    verticalDrop: 1900,
    baseElevation: 6600,
    summitElevation: 8500,
    avgAnnualSnowfall: 472,
  },
  terrain: {
    beginner: 25,
    intermediate: 40,
    advanced: 35,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.2,
  reviewCount: 423,
  heroImage: '/images/bear-valley-hero.jpg',
  websiteUrl: 'https://www.bearvalley.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'powder', 'uncrowded', 'tree-skiing', 'california', 'central-sierra'],
};
