import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const boreal: Resort = {
  id: 'resort:boreal',
  slug: 'boreal',
  name: 'Boreal Mountain Resort',
  tagline: 'First to open, first to the lifts from the Bay Area',
  description: 'Boreal Mountain Resort is typically the first resort to open each season at Lake Tahoe and is the closest Tahoe resort to the San Francisco Bay Area. The resort specializes in terrain parks and freestyle skiing, with features for all ability levels from beginners to pros. Boreal\'s accessible location right off I-80, night skiing, and focus on parks make it a favorite for after-work sessions and weekend warriors.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3328, lng: -120.3478 },
  nearestCity: 'Truckee, CA',
  distanceFromDenver: 855,
  driveTimeFromDenver: 785,
  stats: {
    skiableAcres: 380,
    liftsCount: 8,
    runsCount: 41,
    verticalDrop: 600,
    baseElevation: 7200,
    summitElevation: 7800,
    avgAnnualSnowfall: 400,
  },
  terrain: {
    beginner: 30,
    intermediate: 55,
    advanced: 15,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 3.8,
  reviewCount: 456,
  heroImage: '/images/boreal-hero.jpg',
  websiteUrl: 'https://www.rideboreal.com',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'terrain-parks', 'night-skiing', 'california', 'accessible'],
};
