import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const chinaPeak: Resort = {
  id: 'resort:china-peak',
  slug: 'china-peak',
  name: 'China Peak',
  tagline: 'Central California\'s premier ski destination',
  description: 'China Peak Mountain Resort (formerly Sierra Summit) is the primary ski destination for California\'s Central Valley, located in the Sierra National Forest above Huntington Lake. The resort offers varied terrain across 1,679 acres with reliable snowfall and a friendly, family-oriented atmosphere. China Peak serves as the ski area of choice for Fresno and the surrounding communities.',
  isActive: true,
  isLost: false,
  location: { lat: 37.2319, lng: -119.1572 },
  nearestCity: 'Lakeshore, CA',
  distanceFromDenver: 830,
  driveTimeFromDenver: 770,
  stats: {
    skiableAcres: 1679,
    liftsCount: 11,
    runsCount: 45,
    verticalDrop: 1673,
    baseElevation: 7030,
    summitElevation: 8703,
    avgAnnualSnowfall: 300,
  },
  terrain: {
    beginner: 25,
    intermediate: 50,
    advanced: 25,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 312,
  heroImage: '/images/china-peak-hero.jpg',
  websiteUrl: 'https://www.skichinapeak.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'family', 'central-california', 'california', 'affordable'],
};
