import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const dodgeRidge: Resort = {
  id: 'resort:dodge-ridge',
  slug: 'dodge-ridge',
  name: 'Dodge Ridge',
  tagline: 'Family skiing in the Stanislaus National Forest',
  description: 'Dodge Ridge is the closest ski resort to the San Francisco Bay Area and Central Valley, making it a popular destination for families and day-trippers. Located in the Stanislaus National Forest near Pinecrest, Dodge Ridge offers a genuine family atmosphere with varied terrain suitable for all ability levels. The resort maintains its focus on affordable, accessible skiing with a welcoming community vibe.',
  isActive: true,
  isLost: false,
  location: { lat: 38.1897, lng: -119.9556 },
  nearestCity: 'Pinecrest, CA',
  distanceFromDenver: 840,
  driveTimeFromDenver: 780,
  stats: {
    skiableAcres: 862,
    liftsCount: 12,
    runsCount: 67,
    verticalDrop: 1600,
    baseElevation: 6600,
    summitElevation: 8200,
    avgAnnualSnowfall: 312,
  },
  terrain: {
    beginner: 20,
    intermediate: 40,
    advanced: 40,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['indy'],
  rating: 4.0,
  reviewCount: 567,
  heroImage: '/images/dodge-ridge-hero.jpg',
  websiteUrl: 'https://www.dodgeridge.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'indy-pass', 'family', 'affordable', 'california', 'accessible'],
};
