import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const donnerSkiRanch: Resort = {
  id: 'resort:donner-ski-ranch',
  slug: 'donner-ski-ranch',
  name: 'Donner Ski Ranch',
  tagline: 'Old-school Tahoe skiing at Donner Summit',
  description: 'Donner Ski Ranch is one of the oldest continuously operating ski areas in California, offering affordable, family-friendly skiing at Donner Summit. The resort maintains its vintage character with a relaxed atmosphere and straightforward approach to skiing. With views of Donner Lake and access to excellent terrain, DSR delivers a throwback experience that regulars treasure.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3178, lng: -120.3297 },
  nearestCity: 'Norden, CA',
  distanceFromDenver: 858,
  driveTimeFromDenver: 788,
  stats: {
    skiableAcres: 505,
    liftsCount: 8,
    runsCount: 52,
    verticalDrop: 750,
    baseElevation: 7031,
    summitElevation: 7781,
    avgAnnualSnowfall: 400,
  },
  terrain: {
    beginner: 25,
    intermediate: 50,
    advanced: 25,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 267,
  heroImage: '/images/donner-ski-ranch-hero.jpg',
  websiteUrl: 'https://www.donnerskiranch.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'historic', 'affordable', 'family', 'california', 'donner-summit'],
};
