import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const juneMountain: Resort = {
  id: 'resort:june-mountain',
  slug: 'june-mountain',
  name: 'June Mountain',
  tagline: 'Mammoth\'s quieter neighbor with local soul',
  description: 'June Mountain is the smaller, quieter sister resort to nearby Mammoth Mountain, offering a more intimate skiing experience with no lift lines and a laid-back atmosphere. Located just 20 miles north of Mammoth in the June Lake Loop, the resort delivers excellent intermediate terrain, fantastic tree skiing, and stunning views of the eastern Sierra. June\'s mellow vibe attracts families and those seeking an escape from crowded slopes.',
  isActive: true,
  isLost: false,
  location: { lat: 37.7675, lng: -119.0903 },
  nearestCity: 'June Lake, CA',
  distanceFromDenver: 750,
  driveTimeFromDenver: 710,
  stats: {
    skiableAcres: 1500,
    liftsCount: 7,
    runsCount: 35,
    verticalDrop: 2590,
    baseElevation: 7545,
    summitElevation: 10135,
    avgAnnualSnowfall: 250,
  },
  terrain: {
    beginner: 35,
    intermediate: 45,
    advanced: 15,
    expert: 5,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.4,
  reviewCount: 345,
  heroImage: '/images/june-mountain-hero.jpg',
  websiteUrl: 'https://www.junemountain.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'uncrowded', 'family', 'california', 'local'],
};
