import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mammothMountain: Resort = {
  id: 'resort:mammoth-mountain',
  slug: 'mammoth-mountain',
  name: 'Mammoth Mountain',
  tagline: 'California\'s highest and snowiest ski resort',
  description: 'Mammoth Mountain is the crown jewel of California skiing, offering the state\'s most extensive terrain and legendary snowfall. Located on the eastern side of the Sierra Nevada, Mammoth regularly receives over 400 inches of snow and maintains one of the longest seasons in North America, often operating into June or July. The resort features diverse terrain across 3,500 acres, from perfectly groomed boulevards to challenging steeps and excellent terrain parks. The Main Lodge and Canyon Lodge areas provide modern amenities, while the town of Mammoth Lakes offers a year-round mountain community atmosphere.',
  isActive: true,
  isLost: false,
  location: { lat: 37.6308, lng: -119.0326 },
  nearestCity: 'Mammoth Lakes, CA',
  distanceFromDenver: 740,
  driveTimeFromDenver: 720,
  stats: {
    skiableAcres: 3500,
    liftsCount: 28,
    runsCount: 150,
    verticalDrop: 3100,
    baseElevation: 7953,
    summitElevation: 11053,
    avgAnnualSnowfall: 400,
  },
  terrain: {
    beginner: 25,
    intermediate: 40,
    advanced: 20,
    expert: 15,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.7,
  reviewCount: 2156,
  heroImage: '/images/mammoth-mountain-hero.jpg',
  websiteUrl: 'https://www.mammothmountain.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/mammothmountain',
    instagram: 'https://www.instagram.com/mammothmountain',
    youtube: 'https://www.youtube.com/mammothmountain',
  },
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'deep-snow', 'long-season', 'california', 'terrain-parks'],
  highSpeedLifts: {
    count: 9,
    items: [
      { name: 'Panorama Gondola', url: 'https://www.mammothmountain.com' },
      { name: 'Village Gondola', url: 'https://www.mammothmountain.com' },
      { name: 'Canyon Express', url: 'https://www.mammothmountain.com' },
      { name: 'Stump Alley Express', url: 'https://www.mammothmountain.com' },
      { name: 'Cloud Nine Express', url: 'https://www.mammothmountain.com' },
    ],
  },
  baseAreas: {
    count: 3,
    items: [
      { name: 'Main Lodge', url: 'https://www.mammothmountain.com' },
      { name: 'Canyon Lodge', url: 'https://www.mammothmountain.com' },
      { name: 'Eagle Lodge', url: 'https://www.mammothmountain.com' },
    ],
  },
};
