import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mountainHigh: Resort = {
  id: 'resort:mountain-high',
  slug: 'mountain-high',
  name: 'Mountain High',
  tagline: 'Southern California\'s closest major ski resort',
  description: 'Mountain High is the closest major ski resort to Los Angeles, located in the San Gabriel Mountains just 90 minutes from downtown. Spanning three separate base areas (West, East, and North), Mountain High offers diverse terrain and Southern California\'s most extensive night skiing. The resort provides an accessible skiing experience for millions of LA-area residents and maintains a fun, social atmosphere with events throughout the season.',
  isActive: true,
  isLost: false,
  location: { lat: 34.3722, lng: -117.6928 },
  nearestCity: 'Wrightwood, CA',
  distanceFromDenver: 780,
  driveTimeFromDenver: 720,
  stats: {
    skiableAcres: 290,
    liftsCount: 16,
    runsCount: 59,
    verticalDrop: 1600,
    baseElevation: 6600,
    summitElevation: 8200,
    avgAnnualSnowfall: 144,
  },
  terrain: {
    beginner: 25,
    intermediate: 40,
    advanced: 25,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 3.9,
  reviewCount: 892,
  heroImage: '/images/mountain-high-hero.jpg',
  websiteUrl: 'https://www.mthigh.com',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'night-skiing', 'socal', 'california', 'accessible'],
};
