import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mtShasta: Resort = {
  id: 'resort:mt-shasta',
  slug: 'mt-shasta',
  name: 'Mt. Shasta Ski Park',
  tagline: 'Skiing in the shadow of California\'s iconic volcanic peak',
  description: 'Mt. Shasta Ski Park offers affordable skiing on the slopes of Mount Shasta, Northern California\'s iconic volcanic peak. The resort provides a low-key, family-friendly experience with varied terrain and spectacular views of the surrounding Cascade Range. Night skiing and an excellent park program add to the appeal for locals from Redding and the surrounding communities.',
  isActive: true,
  isLost: false,
  location: { lat: 41.3200, lng: -122.2019 },
  nearestCity: 'Mt. Shasta, CA',
  distanceFromDenver: 950,
  driveTimeFromDenver: 880,
  stats: {
    skiableAcres: 425,
    liftsCount: 5,
    runsCount: 32,
    verticalDrop: 1435,
    baseElevation: 5500,
    summitElevation: 6935,
    avgAnnualSnowfall: 275,
  },
  terrain: {
    beginner: 20,
    intermediate: 60,
    advanced: 20,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.1,
  reviewCount: 234,
  heroImage: '/images/mt-shasta-hero.jpg',
  websiteUrl: 'https://www.skipark.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'volcanic', 'night-skiing', 'northern-california', 'california', 'affordable'],
};
