import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const sierraAtTahoe: Resort = {
  id: 'resort:sierra-at-tahoe',
  slug: 'sierra-at-tahoe',
  name: 'Sierra-at-Tahoe',
  tagline: 'Lake Tahoe\'s friendly neighborhood mountain',
  description: 'Sierra-at-Tahoe offers a welcoming, family-friendly atmosphere on the south shore of Lake Tahoe. Known for excellent tree skiing and a laid-back vibe, Sierra provides diverse terrain without the crowds of larger Tahoe resorts. The resort was significantly impacted by the 2021 Caldor Fire but has been rebuilding and continues to offer quality skiing. Affordable lift tickets and a genuine community atmosphere make Sierra a favorite among locals.',
  isActive: true,
  isLost: false,
  location: { lat: 38.7994, lng: -120.0800 },
  nearestCity: 'Twin Bridges, CA',
  distanceFromDenver: 900,
  driveTimeFromDenver: 820,
  stats: {
    skiableAcres: 2000,
    liftsCount: 14,
    runsCount: 46,
    verticalDrop: 2212,
    baseElevation: 6640,
    summitElevation: 8852,
    avgAnnualSnowfall: 480,
  },
  terrain: {
    beginner: 25,
    intermediate: 50,
    advanced: 25,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.3,
  reviewCount: 756,
  heroImage: '/images/sierra-at-tahoe-hero.jpg',
  websiteUrl: 'https://www.sierraattahoe.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'family', 'tree-skiing', 'california', 'affordable'],
};
