import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const snowValley: Resort = {
  id: 'resort:snow-valley',
  slug: 'snow-valley',
  name: 'Snow Valley',
  tagline: 'Affordable family skiing in the San Bernardino Mountains',
  description: 'Snow Valley Mountain Resort in Running Springs offers affordable family skiing in the San Bernardino Mountains, positioned between Big Bear and Lake Arrowhead. The resort focuses on providing a welcoming, low-key environment for families and beginners, with quality instruction programs and affordable lift tickets. Snow Valley\'s uncrowded slopes and genuine mountain atmosphere make it a favorite alternative to larger Southern California resorts.',
  isActive: true,
  isLost: false,
  location: { lat: 34.2242, lng: -117.0375 },
  nearestCity: 'Running Springs, CA',
  distanceFromDenver: 765,
  driveTimeFromDenver: 705,
  stats: {
    skiableAcres: 240,
    liftsCount: 13,
    runsCount: 28,
    verticalDrop: 1141,
    baseElevation: 6800,
    summitElevation: 7841,
    avgAnnualSnowfall: 120,
  },
  terrain: {
    beginner: 30,
    intermediate: 50,
    advanced: 20,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 345,
  heroImage: '/images/snow-valley-hero.jpg',
  websiteUrl: 'https://www.snow-valley.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'family', 'affordable', 'socal', 'california', 'beginner-friendly'],
};
