import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const snowSummit: Resort = {
  id: 'resort:snow-summit',
  slug: 'snow-summit',
  name: 'Snow Summit',
  tagline: 'Big Bear\'s family-friendly ski experience',
  description: 'Snow Summit is one of two ski resorts in Big Bear Lake, offering a family-friendly atmosphere and varied terrain. Connected to nearby Bear Mountain by shuttle, the two resorts can be skied on a single ticket. Snow Summit focuses on traditional skiing with excellent grooming and a welcoming vibe that has made it a Southern California institution for generations of skiers.',
  isActive: true,
  isLost: false,
  location: { lat: 34.2306, lng: -116.8897 },
  nearestCity: 'Big Bear Lake, CA',
  distanceFromDenver: 760,
  driveTimeFromDenver: 700,
  stats: {
    skiableAcres: 240,
    liftsCount: 14,
    runsCount: 31,
    verticalDrop: 1200,
    baseElevation: 7000,
    summitElevation: 8200,
    avgAnnualSnowfall: 100,
  },
  terrain: {
    beginner: 40,
    intermediate: 35,
    advanced: 15,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.0,
  reviewCount: 567,
  heroImage: '/images/snow-summit-hero.jpg',
  websiteUrl: 'https://www.bigbearmountainresort.com/snow-summit',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'family', 'socal', 'california', 'big-bear'],
};
