import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const sodaSprings: Resort = {
  id: 'resort:soda-springs',
  slug: 'soda-springs',
  name: 'Soda Springs',
  tagline: 'California\'s original ski resort and tubing paradise',
  description: 'Soda Springs is California\'s oldest ski resort, having opened in 1931, and now focuses primarily on family fun with an emphasis on tubing and introductory skiing. Located at Donner Summit, the resort provides a gentle, welcoming environment perfect for young children and first-time snow visitors. Planet Kids and the tubing hills draw families from across Northern California for a low-pressure snow experience.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3186, lng: -120.3806 },
  nearestCity: 'Soda Springs, CA',
  distanceFromDenver: 860,
  driveTimeFromDenver: 790,
  stats: {
    skiableAcres: 200,
    liftsCount: 4,
    runsCount: 15,
    verticalDrop: 652,
    baseElevation: 6768,
    summitElevation: 7352,
    avgAnnualSnowfall: 400,
  },
  terrain: {
    beginner: 70,
    intermediate: 25,
    advanced: 5,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 678,
  heroImage: '/images/soda-springs-hero.jpg',
  websiteUrl: 'https://www.skisodasprings.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'family', 'beginner-friendly', 'tubing', 'california', 'historic'],
};
