import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const tahoeDonner: Resort = {
  id: 'resort:tahoe-donner',
  slug: 'tahoe-donner',
  name: 'Tahoe Donner',
  tagline: 'The ultimate beginner and family ski experience',
  description: 'Tahoe Donner Downhill Ski Resort is consistently rated as one of the best places in the country to learn to ski. Part of the Tahoe Donner homeowners association, the resort focuses exclusively on beginners and families, with gentle terrain, excellent instruction, and a supportive atmosphere. The separate cross-country center offers some of the best Nordic skiing in California.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3539, lng: -120.2350 },
  nearestCity: 'Truckee, CA',
  distanceFromDenver: 870,
  driveTimeFromDenver: 800,
  stats: {
    skiableAcres: 120,
    liftsCount: 5,
    runsCount: 14,
    verticalDrop: 600,
    baseElevation: 6750,
    summitElevation: 7350,
    avgAnnualSnowfall: 300,
  },
  terrain: {
    beginner: 75,
    intermediate: 25,
    advanced: 0,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.3,
  reviewCount: 345,
  heroImage: '/images/tahoe-donner-hero.jpg',
  websiteUrl: 'https://www.tahoedonner.com/downhill-ski',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'beginner-friendly', 'family', 'lessons', 'california', 'learn-to-ski'],
};
