import { Resort } from './types';

export const mockResorts: Resort[] = [
  {
    id: 'resort:vail',
    slug: 'vail',
    name: 'Vail Ski Resort',
    tagline: 'Legendary Back Bowls and upscale village charm',
    description: 'The crown jewel of Colorado skiing, featuring vast terrain including the famous Back Bowls.',
    location: { lat: 39.6061, lng: -106.3550 },
    nearestCity: 'Vail, CO',
    distanceFromDenver: 100,
    driveTimeFromDenver: 120,
    stats: {
      skiableAcres: 5289,
      liftsCount: 31,
      runsCount: 195,
      verticalDrop: 3450,
      baseElevation: 8120,
      summitElevation: 11570,
      avgAnnualSnowfall: 354,
    },
    terrain: {
      beginner: 18,
      intermediate: 29,
      advanced: 31,
      expert: 22,
    },
    conditions: {
      snowfall24h: 12,
      snowfall72h: 24,
      baseDepth: 85,
      terrainOpen: 95,
      liftsOpen: 29,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.8,
    reviewCount: 2347,
    heroImage: 'https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'epic-pass', 'bowls', 'upscale', 'large'],
  },
  {
    id: 'resort:breckenridge',
    slug: 'breckenridge',
    name: 'Breckenridge Ski Resort',
    tagline: 'Five peaks of adventure above a historic mining town',
    description: 'Colorado\'s most visited ski resort with diverse terrain across five peaks.',
    location: { lat: 39.4817, lng: -106.0384 },
    nearestCity: 'Breckenridge, CO',
    distanceFromDenver: 85,
    driveTimeFromDenver: 105,
    stats: {
      skiableAcres: 2908,
      liftsCount: 35,
      runsCount: 187,
      verticalDrop: 3398,
      baseElevation: 9600,
      summitElevation: 12998,
      avgAnnualSnowfall: 353,
    },
    terrain: {
      beginner: 14,
      intermediate: 31,
      advanced: 36,
      expert: 19,
    },
    conditions: {
      snowfall24h: 8,
      snowfall72h: 18,
      baseDepth: 78,
      terrainOpen: 88,
      liftsOpen: 32,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.7,
    reviewCount: 3142,
    heroImage: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['destination', 'epic-pass', 'town', 'family-friendly', 'large'],
  },
  {
    id: 'resort:aspen-snowmass',
    slug: 'aspen-snowmass',
    name: 'Aspen Snowmass',
    tagline: 'Four mountains, one unforgettable experience',
    description: 'Four distinct mountains offering everything from gentle groomers to extreme steeps.',
    location: { lat: 39.2091, lng: -106.9461 },
    nearestCity: 'Aspen, CO',
    distanceFromDenver: 200,
    driveTimeFromDenver: 240,
    stats: {
      skiableAcres: 5527,
      liftsCount: 42,
      runsCount: 336,
      verticalDrop: 4406,
      baseElevation: 7945,
      summitElevation: 12351,
      avgAnnualSnowfall: 300,
    },
    terrain: {
      beginner: 20,
      intermediate: 36,
      advanced: 26,
      expert: 18,
    },
    conditions: {
      snowfall24h: 15,
      snowfall72h: 22,
      baseDepth: 92,
      terrainOpen: 90,
      liftsOpen: 39,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.9,
    reviewCount: 1876,
    heroImage: 'https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'ikon-pass', 'luxury', 'four-mountains', 'large'],
  },
  {
    id: 'resort:steamboat',
    slug: 'steamboat',
    name: 'Steamboat Resort',
    tagline: 'Ski Town USA with legendary Champagne Powder',
    description: 'Famous for its consistent Champagne Powder snow and authentic western atmosphere.',
    location: { lat: 40.4850, lng: -106.8317 },
    nearestCity: 'Steamboat Springs, CO',
    distanceFromDenver: 165,
    driveTimeFromDenver: 195,
    stats: {
      skiableAcres: 2965,
      liftsCount: 18,
      runsCount: 169,
      verticalDrop: 3668,
      baseElevation: 6900,
      summitElevation: 10568,
      avgAnnualSnowfall: 349,
    },
    terrain: {
      beginner: 14,
      intermediate: 42,
      advanced: 44,
      expert: 0,
    },
    conditions: {
      snowfall24h: 10,
      snowfall72h: 20,
      baseDepth: 88,
      terrainOpen: 92,
      liftsOpen: 17,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.8,
    reviewCount: 1654,
    heroImage: 'https://images.unsplash.com/photo-1543785734-4b6e564642f8?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: true,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['destination', 'ikon-pass', 'champagne-powder', 'western', 'large'],
  },
  {
    id: 'resort:arapahoe-basin',
    slug: 'arapahoe-basin',
    name: 'Arapahoe Basin',
    tagline: 'The Legend - High altitude expert terrain',
    description: 'Known for steep terrain, late-season skiing, and no-frills mountain experience.',
    location: { lat: 39.6425, lng: -105.8719 },
    nearestCity: 'Dillon, CO',
    distanceFromDenver: 68,
    driveTimeFromDenver: 75,
    stats: {
      skiableAcres: 1428,
      liftsCount: 9,
      runsCount: 147,
      verticalDrop: 2530,
      baseElevation: 10780,
      summitElevation: 13050,
      avgAnnualSnowfall: 350,
    },
    terrain: {
      beginner: 10,
      intermediate: 30,
      advanced: 28,
      expert: 32,
    },
    conditions: {
      snowfall24h: 14,
      snowfall72h: 28,
      baseDepth: 96,
      terrainOpen: 85,
      liftsOpen: 8,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.7,
    reviewCount: 987,
    heroImage: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800',
    features: {
      hasPark: false,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['expert', 'ikon-pass', 'high-altitude', 'steep', 'medium'],
  },
  {
    id: 'resort:loveland',
    slug: 'loveland',
    name: 'Loveland Ski Area',
    tagline: 'High and dry - closest to Denver',
    description: 'The closest major ski area to Denver, offering great snow and value.',
    location: { lat: 39.6804, lng: -105.8978 },
    nearestCity: 'Georgetown, CO',
    distanceFromDenver: 56,
    driveTimeFromDenver: 65,
    stats: {
      skiableAcres: 1800,
      liftsCount: 10,
      runsCount: 94,
      verticalDrop: 2210,
      baseElevation: 10800,
      summitElevation: 13010,
      avgAnnualSnowfall: 422,
    },
    terrain: {
      beginner: 13,
      intermediate: 41,
      advanced: 46,
      expert: 0,
    },
    conditions: {
      snowfall24h: 16,
      snowfall72h: 30,
      baseDepth: 102,
      terrainOpen: 90,
      liftsOpen: 9,
      status: 'open',
    },
    passAffiliations: ['local'],
    rating: 4.6,
    reviewCount: 1234,
    heroImage: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['near-denver', 'value', 'high-altitude', 'medium'],
  },
  {
    id: 'resort:copper',
    slug: 'copper',
    name: 'Copper Mountain',
    tagline: 'Naturally divided terrain for every ability',
    description: 'Unique layout with terrain naturally divided by ability level across the mountain.',
    location: { lat: 39.5019, lng: -106.1503 },
    nearestCity: 'Copper Mountain, CO',
    distanceFromDenver: 75,
    driveTimeFromDenver: 90,
    stats: {
      skiableAcres: 2490,
      liftsCount: 24,
      runsCount: 150,
      verticalDrop: 2601,
      baseElevation: 9712,
      summitElevation: 12313,
      avgAnnualSnowfall: 305,
    },
    terrain: {
      beginner: 21,
      intermediate: 25,
      advanced: 36,
      expert: 18,
    },
    conditions: {
      snowfall24h: 9,
      snowfall72h: 20,
      baseDepth: 80,
      terrainOpen: 87,
      liftsOpen: 22,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.5,
    reviewCount: 1456,
    heroImage: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['ikon-pass', 'family-friendly', 'divided-terrain', 'large'],
  },
  {
    id: 'resort:winter-park',
    slug: 'winter-park',
    name: 'Winter Park Resort',
    tagline: 'Denver\'s favorite mountain',
    description: 'Expansive terrain with legendary tree skiing and accessibility from Denver.',
    location: { lat: 39.8868, lng: -105.7625 },
    nearestCity: 'Winter Park, CO',
    distanceFromDenver: 67,
    driveTimeFromDenver: 85,
    stats: {
      skiableAcres: 3081,
      liftsCount: 25,
      runsCount: 168,
      verticalDrop: 3060,
      baseElevation: 9000,
      summitElevation: 12060,
      avgAnnualSnowfall: 347,
    },
    terrain: {
      beginner: 9,
      intermediate: 17,
      advanced: 47,
      expert: 27,
    },
    conditions: {
      snowfall24h: 7,
      snowfall72h: 15,
      baseDepth: 75,
      terrainOpen: 82,
      liftsOpen: 23,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.6,
    reviewCount: 1789,
    heroImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['ikon-pass', 'trees', 'near-denver', 'large'],
  },
  {
    id: 'resort:keystone',
    slug: 'keystone',
    name: 'Keystone Resort',
    tagline: 'Night skiing and family adventure',
    description: 'Colorado\'s premier night skiing destination with extensive family amenities.',
    location: { lat: 39.5791, lng: -105.9347 },
    nearestCity: 'Keystone, CO',
    distanceFromDenver: 74,
    driveTimeFromDenver: 90,
    stats: {
      skiableAcres: 3148,
      liftsCount: 20,
      runsCount: 131,
      verticalDrop: 3128,
      baseElevation: 9280,
      summitElevation: 12408,
      avgAnnualSnowfall: 235,
    },
    terrain: {
      beginner: 14,
      intermediate: 32,
      advanced: 41,
      expert: 13,
    },
    conditions: {
      snowfall24h: 6,
      snowfall72h: 14,
      baseDepth: 68,
      terrainOpen: 78,
      liftsOpen: 18,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.4,
    reviewCount: 1523,
    heroImage: 'https://images.unsplash.com/photo-1547498575-853bad4e1e6c?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: true,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['epic-pass', 'night-skiing', 'family-friendly', 'large'],
  },
  {
    id: 'resort:telluride',
    slug: 'telluride',
    name: 'Telluride Ski Resort',
    tagline: 'The most beautiful place you\'ll ever ski',
    description: 'Dramatic San Juan Mountain setting with challenging terrain and stunning views.',
    location: { lat: 37.9375, lng: -107.8123 },
    nearestCity: 'Telluride, CO',
    distanceFromDenver: 330,
    driveTimeFromDenver: 390,
    stats: {
      skiableAcres: 2000,
      liftsCount: 18,
      runsCount: 148,
      verticalDrop: 4425,
      baseElevation: 8725,
      summitElevation: 13150,
      avgAnnualSnowfall: 309,
    },
    terrain: {
      beginner: 23,
      intermediate: 36,
      advanced: 41,
      expert: 0,
    },
    conditions: {
      snowfall24h: 11,
      snowfall72h: 19,
      baseDepth: 84,
      terrainOpen: 86,
      liftsOpen: 16,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.9,
    reviewCount: 892,
    heroImage: 'https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800',
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'ikon-pass', 'scenic', 'expert', 'large'],
  },
];
