import { Resort } from './types';

export const mockResorts: Resort[] = [
  {
    id: 'resort:vail',
    slug: 'vail',
    name: 'Vail Ski Resort',
    tagline: 'Legendary Back Bowls and upscale village charm',
    description: 'The crown jewel of Colorado skiing, featuring vast terrain including the famous Back Bowls.',
    location: { lat: 39.6061, lng: -106.3550 },
    nearestCity: 'Vail, CO',
    distanceFromDenver: 100,
    driveTimeFromDenver: 120,
    stats: {
      skiableAcres: 5289,
      liftsCount: 31,
      runsCount: 195,
      verticalDrop: 3450,
      baseElevation: 8120,
      summitElevation: 11570,
      avgAnnualSnowfall: 354,
    },
    terrain: {
      beginner: 18,
      intermediate: 29,
      advanced: 31,
      expert: 22,
    },
    conditions: {
      snowfall24h: 12,
      snowfall72h: 24,
      baseDepth: 85,
      terrainOpen: 95,
      liftsOpen: 29,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.8,
    reviewCount: 2347,
    heroImage: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200',
    weather: {
      current: {
        temp: 28,
        condition: 'Partly Cloudy',
        windSpeed: 12,
        humidity: 65,
      },
      forecast: [
        { day: 'Mon', high: 32, low: 18, condition: 'Snowy', snowChance: 80 },
        { day: 'Tue', high: 28, low: 15, condition: 'Heavy Snow', snowChance: 95 },
        { day: 'Wed', high: 25, low: 12, condition: 'Cloudy', snowChance: 40 },
        { day: 'Thu', high: 30, low: 20, condition: 'Sunny', snowChance: 10 },
        { day: 'Fri', high: 35, low: 22, condition: 'Partly Cloudy', snowChance: 30 },
        { day: 'Sat', high: 38, low: 25, condition: 'Snowy', snowChance: 70 },
        { day: 'Sun', high: 33, low: 19, condition: 'Cloudy', snowChance: 50 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/vail',
      instagram: 'https://www.instagram.com/vailmtn',
      youtube: 'https://www.youtube.com/@vail',
      tiktok: 'https://www.tiktok.com/@vailmountain',
      x: 'https://twitter.com/vailmtn',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'epic-pass', 'bowls', 'upscale', 'large'],
  },
  {
    id: 'resort:breckenridge',
    slug: 'breckenridge',
    name: 'Breckenridge Ski Resort',
    tagline: 'Five peaks of adventure above a historic mining town',
    description: 'Colorado\'s most visited ski resort with diverse terrain across five peaks.',
    location: { lat: 39.4817, lng: -106.0384 },
    nearestCity: 'Breckenridge, CO',
    distanceFromDenver: 85,
    driveTimeFromDenver: 105,
    stats: {
      skiableAcres: 2908,
      liftsCount: 35,
      runsCount: 187,
      verticalDrop: 3398,
      baseElevation: 9600,
      summitElevation: 12998,
      avgAnnualSnowfall: 353,
    },
    terrain: {
      beginner: 14,
      intermediate: 31,
      advanced: 36,
      expert: 19,
    },
    conditions: {
      snowfall24h: 8,
      snowfall72h: 18,
      baseDepth: 78,
      terrainOpen: 88,
      liftsOpen: 32,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.7,
    reviewCount: 3142,
    heroImage: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=1200',
    weather: {
      current: {
        temp: 26,
        condition: 'Snowy',
        windSpeed: 15,
        humidity: 72,
      },
      forecast: [
        { day: 'Mon', high: 30, low: 16, condition: 'Heavy Snow', snowChance: 90 },
        { day: 'Tue', high: 27, low: 14, condition: 'Snowy', snowChance: 85 },
        { day: 'Wed', high: 24, low: 10, condition: 'Partly Cloudy', snowChance: 35 },
        { day: 'Thu', high: 29, low: 18, condition: 'Sunny', snowChance: 15 },
        { day: 'Fri', high: 34, low: 21, condition: 'Cloudy', snowChance: 40 },
        { day: 'Sat', high: 36, low: 23, condition: 'Snowy', snowChance: 75 },
        { day: 'Sun', high: 31, low: 17, condition: 'Partly Cloudy', snowChance: 45 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/breckenridge',
      instagram: 'https://www.instagram.com/breckenridgemtn',
      youtube: 'https://www.youtube.com/@breckenridge',
      tiktok: 'https://www.tiktok.com/@breckenridgemtn',
      x: 'https://twitter.com/breckenridgemtn',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['destination', 'epic-pass', 'town', 'family-friendly', 'large'],
  },
  {
    id: 'resort:aspen-snowmass',
    slug: 'aspen-snowmass',
    name: 'Aspen Snowmass',
    tagline: 'Four mountains, one unforgettable experience',
    description: 'Four distinct mountains offering everything from gentle groomers to extreme steeps.',
    location: { lat: 39.2091, lng: -106.9461 },
    nearestCity: 'Aspen, CO',
    distanceFromDenver: 200,
    driveTimeFromDenver: 240,
    stats: {
      skiableAcres: 5527,
      liftsCount: 42,
      runsCount: 336,
      verticalDrop: 4406,
      baseElevation: 7945,
      summitElevation: 12351,
      avgAnnualSnowfall: 300,
    },
    terrain: {
      beginner: 20,
      intermediate: 36,
      advanced: 26,
      expert: 18,
    },
    conditions: {
      snowfall24h: 15,
      snowfall72h: 22,
      baseDepth: 92,
      terrainOpen: 90,
      liftsOpen: 39,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.9,
    reviewCount: 1876,
    heroImage: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?w=1200',
    weather: {
      current: {
        temp: 24,
        condition: 'Snowy',
        windSpeed: 10,
        humidity: 68,
      },
      forecast: [
        { day: 'Mon', high: 28, low: 14, condition: 'Heavy Snow', snowChance: 85 },
        { day: 'Tue', high: 25, low: 12, condition: 'Snowy', snowChance: 80 },
        { day: 'Wed', high: 22, low: 8, condition: 'Partly Cloudy', snowChance: 30 },
        { day: 'Thu', high: 27, low: 16, condition: 'Sunny', snowChance: 10 },
        { day: 'Fri', high: 32, low: 19, condition: 'Cloudy', snowChance: 35 },
        { day: 'Sat', high: 34, low: 21, condition: 'Snowy', snowChance: 70 },
        { day: 'Sun', high: 29, low: 15, condition: 'Partly Cloudy', snowChance: 40 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/AspenSnowmass',
      instagram: 'https://www.instagram.com/aspensnowmass',
      youtube: 'https://www.youtube.com/@aspensnowmass',
      x: 'https://twitter.com/aspensnowmass',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'ikon-pass', 'luxury', 'four-mountains', 'large'],
  },
  {
    id: 'resort:steamboat',
    slug: 'steamboat',
    name: 'Steamboat Resort',
    tagline: 'Ski Town USA with legendary Champagne Powder',
    description: 'Famous for its consistent Champagne Powder snow and authentic western atmosphere.',
    location: { lat: 40.4850, lng: -106.8317 },
    nearestCity: 'Steamboat Springs, CO',
    distanceFromDenver: 165,
    driveTimeFromDenver: 195,
    stats: {
      skiableAcres: 2965,
      liftsCount: 18,
      runsCount: 169,
      verticalDrop: 3668,
      baseElevation: 6900,
      summitElevation: 10568,
      avgAnnualSnowfall: 349,
    },
    terrain: {
      beginner: 14,
      intermediate: 42,
      advanced: 44,
      expert: 0,
    },
    conditions: {
      snowfall24h: 10,
      snowfall72h: 20,
      baseDepth: 88,
      terrainOpen: 92,
      liftsOpen: 17,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.8,
    reviewCount: 1654,
    heroImage: 'https://images.unsplash.com/photo-1498429089284-41f8cf3ffd39?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1498429089284-41f8cf3ffd39?w=1200',
    weather: {
      current: {
        temp: 22,
        condition: 'Heavy Snow',
        windSpeed: 18,
        humidity: 75,
      },
      forecast: [
        { day: 'Mon', high: 26, low: 12, condition: 'Heavy Snow', snowChance: 92 },
        { day: 'Tue', high: 24, low: 10, condition: 'Snowy', snowChance: 88 },
        { day: 'Wed', high: 20, low: 6, condition: 'Cloudy', snowChance: 45 },
        { day: 'Thu', high: 25, low: 14, condition: 'Partly Cloudy', snowChance: 20 },
        { day: 'Fri', high: 30, low: 17, condition: 'Sunny', snowChance: 15 },
        { day: 'Sat', high: 32, low: 19, condition: 'Snowy', snowChance: 75 },
        { day: 'Sun', high: 27, low: 13, condition: 'Cloudy', snowChance: 50 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/steamboat',
      instagram: 'https://www.instagram.com/steamboatresort',
      youtube: 'https://www.youtube.com/@steamboatresort',
      tiktok: 'https://www.tiktok.com/@steamboatresort',
      x: 'https://twitter.com/steamboatresort',
    },
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: true,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['destination', 'ikon-pass', 'champagne-powder', 'western', 'large'],
  },
  {
    id: 'resort:arapahoe-basin',
    slug: 'arapahoe-basin',
    name: 'Arapahoe Basin',
    tagline: 'The Legend - High altitude expert terrain',
    description: 'Known for steep terrain, late-season skiing, and no-frills mountain experience.',
    location: { lat: 39.6425, lng: -105.8719 },
    nearestCity: 'Dillon, CO',
    distanceFromDenver: 68,
    driveTimeFromDenver: 75,
    stats: {
      skiableAcres: 1428,
      liftsCount: 9,
      runsCount: 147,
      verticalDrop: 2530,
      baseElevation: 10780,
      summitElevation: 13050,
      avgAnnualSnowfall: 350,
    },
    terrain: {
      beginner: 10,
      intermediate: 30,
      advanced: 28,
      expert: 32,
    },
    conditions: {
      snowfall24h: 14,
      snowfall72h: 28,
      baseDepth: 96,
      terrainOpen: 85,
      liftsOpen: 8,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.7,
    reviewCount: 987,
    heroImage: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1200',
    weather: {
      current: {
        temp: 18,
        condition: 'Partly Cloudy',
        windSpeed: 22,
        humidity: 60,
      },
      forecast: [
        { day: 'Mon', high: 22, low: 8, condition: 'Snowy', snowChance: 75 },
        { day: 'Tue', high: 20, low: 6, condition: 'Heavy Snow', snowChance: 90 },
        { day: 'Wed', high: 16, low: 2, condition: 'Cloudy', snowChance: 40 },
        { day: 'Thu', high: 21, low: 10, condition: 'Sunny', snowChance: 5 },
        { day: 'Fri', high: 26, low: 13, condition: 'Partly Cloudy', snowChance: 25 },
        { day: 'Sat', high: 28, low: 15, condition: 'Snowy', snowChance: 65 },
        { day: 'Sun', high: 23, low: 9, condition: 'Cloudy', snowChance: 55 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/arapahoebasin',
      instagram: 'https://www.instagram.com/arapahoebasin',
      youtube: 'https://www.youtube.com/@arapahoebasin',
      x: 'https://twitter.com/arapahoebasin',
    },
    features: {
      hasPark: false,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['expert', 'ikon-pass', 'high-altitude', 'steep', 'medium'],
  },
  {
    id: 'resort:loveland',
    slug: 'loveland',
    name: 'Loveland Ski Area',
    tagline: 'High and dry - closest to Denver',
    description: 'The closest major ski area to Denver, offering great snow and value.',
    location: { lat: 39.6804, lng: -105.8978 },
    nearestCity: 'Georgetown, CO',
    distanceFromDenver: 56,
    driveTimeFromDenver: 65,
    stats: {
      skiableAcres: 1800,
      liftsCount: 10,
      runsCount: 94,
      verticalDrop: 2210,
      baseElevation: 10800,
      summitElevation: 13010,
      avgAnnualSnowfall: 422,
    },
    terrain: {
      beginner: 13,
      intermediate: 41,
      advanced: 46,
      expert: 0,
    },
    conditions: {
      snowfall24h: 16,
      snowfall72h: 30,
      baseDepth: 102,
      terrainOpen: 90,
      liftsOpen: 9,
      status: 'open',
    },
    passAffiliations: ['local'],
    rating: 4.6,
    reviewCount: 1234,
    heroImage: 'https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=1200',
    weather: {
      current: {
        temp: 20,
        condition: 'Snowy',
        windSpeed: 16,
        humidity: 70,
      },
      forecast: [
        { day: 'Mon', high: 24, low: 10, condition: 'Heavy Snow', snowChance: 88 },
        { day: 'Tue', high: 22, low: 8, condition: 'Snowy', snowChance: 82 },
        { day: 'Wed', high: 18, low: 4, condition: 'Partly Cloudy', snowChance: 35 },
        { day: 'Thu', high: 23, low: 12, condition: 'Sunny', snowChance: 12 },
        { day: 'Fri', high: 28, low: 15, condition: 'Cloudy', snowChance: 38 },
        { day: 'Sat', high: 30, low: 17, condition: 'Snowy', snowChance: 72 },
        { day: 'Sun', high: 25, low: 11, condition: 'Partly Cloudy', snowChance: 48 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/skiloveland',
      instagram: 'https://www.instagram.com/skiloveland',
      youtube: 'https://www.youtube.com/@skiloveland',
      x: 'https://twitter.com/skiloveland',
    },
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: false,
    },
    tags: ['near-denver', 'value', 'high-altitude', 'medium'],
  },
  {
    id: 'resort:copper',
    slug: 'copper',
    name: 'Copper Mountain',
    tagline: 'Naturally divided terrain for every ability',
    description: 'Unique layout with terrain naturally divided by ability level across the mountain.',
    location: { lat: 39.5019, lng: -106.1503 },
    nearestCity: 'Copper Mountain, CO',
    distanceFromDenver: 75,
    driveTimeFromDenver: 90,
    stats: {
      skiableAcres: 2490,
      liftsCount: 24,
      runsCount: 150,
      verticalDrop: 2601,
      baseElevation: 9712,
      summitElevation: 12313,
      avgAnnualSnowfall: 305,
    },
    terrain: {
      beginner: 21,
      intermediate: 25,
      advanced: 36,
      expert: 18,
    },
    conditions: {
      snowfall24h: 9,
      snowfall72h: 20,
      baseDepth: 80,
      terrainOpen: 87,
      liftsOpen: 22,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.5,
    reviewCount: 1456,
    heroImage: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200',
    weather: {
      current: {
        temp: 27,
        condition: 'Cloudy',
        windSpeed: 14,
        humidity: 64,
      },
      forecast: [
        { day: 'Mon', high: 31, low: 17, condition: 'Snowy', snowChance: 78 },
        { day: 'Tue', high: 29, low: 15, condition: 'Snowy', snowChance: 73 },
        { day: 'Wed', high: 26, low: 12, condition: 'Partly Cloudy', snowChance: 32 },
        { day: 'Thu', high: 32, low: 20, condition: 'Sunny', snowChance: 8 },
        { day: 'Fri', high: 36, low: 23, condition: 'Partly Cloudy', snowChance: 28 },
        { day: 'Sat', high: 38, low: 25, condition: 'Snowy', snowChance: 68 },
        { day: 'Sun', high: 33, low: 19, condition: 'Cloudy', snowChance: 52 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/coppermtn',
      instagram: 'https://www.instagram.com/coppermtn',
      youtube: 'https://www.youtube.com/@coppermountain',
      tiktok: 'https://www.tiktok.com/@coppermtn',
      x: 'https://twitter.com/coppermtn',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['ikon-pass', 'family-friendly', 'divided-terrain', 'large'],
  },
  {
    id: 'resort:winter-park',
    slug: 'winter-park',
    name: 'Winter Park Resort',
    tagline: 'Denver\'s favorite mountain',
    description: 'Expansive terrain with legendary tree skiing and accessibility from Denver.',
    location: { lat: 39.8868, lng: -105.7625 },
    nearestCity: 'Winter Park, CO',
    distanceFromDenver: 67,
    driveTimeFromDenver: 85,
    stats: {
      skiableAcres: 3081,
      liftsCount: 25,
      runsCount: 168,
      verticalDrop: 3060,
      baseElevation: 9000,
      summitElevation: 12060,
      avgAnnualSnowfall: 347,
    },
    terrain: {
      beginner: 9,
      intermediate: 17,
      advanced: 47,
      expert: 27,
    },
    conditions: {
      snowfall24h: 7,
      snowfall72h: 15,
      baseDepth: 75,
      terrainOpen: 82,
      liftsOpen: 23,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.6,
    reviewCount: 1789,
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
    weather: {
      current: {
        temp: 25,
        condition: 'Partly Cloudy',
        windSpeed: 13,
        humidity: 66,
      },
      forecast: [
        { day: 'Mon', high: 29, low: 15, condition: 'Snowy', snowChance: 76 },
        { day: 'Tue', high: 27, low: 13, condition: 'Snowy', snowChance: 71 },
        { day: 'Wed', high: 24, low: 10, condition: 'Cloudy', snowChance: 36 },
        { day: 'Thu', high: 30, low: 18, condition: 'Sunny', snowChance: 14 },
        { day: 'Fri', high: 34, low: 21, condition: 'Partly Cloudy', snowChance: 31 },
        { day: 'Sat', high: 36, low: 23, condition: 'Snowy', snowChance: 69 },
        { day: 'Sun', high: 31, low: 17, condition: 'Cloudy', snowChance: 49 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/winterparkresort',
      instagram: 'https://www.instagram.com/winterparkresort',
      youtube: 'https://www.youtube.com/@winterparkresort',
      x: 'https://twitter.com/winterparkride',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: false,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['ikon-pass', 'trees', 'near-denver', 'large'],
  },
  {
    id: 'resort:keystone',
    slug: 'keystone',
    name: 'Keystone Resort',
    tagline: 'Night skiing and family adventure',
    description: 'Colorado\'s premier night skiing destination with extensive family amenities.',
    location: { lat: 39.5791, lng: -105.9347 },
    nearestCity: 'Keystone, CO',
    distanceFromDenver: 74,
    driveTimeFromDenver: 90,
    stats: {
      skiableAcres: 3148,
      liftsCount: 20,
      runsCount: 131,
      verticalDrop: 3128,
      baseElevation: 9280,
      summitElevation: 12408,
      avgAnnualSnowfall: 235,
    },
    terrain: {
      beginner: 14,
      intermediate: 32,
      advanced: 41,
      expert: 13,
    },
    conditions: {
      snowfall24h: 6,
      snowfall72h: 14,
      baseDepth: 68,
      terrainOpen: 78,
      liftsOpen: 18,
      status: 'open',
    },
    passAffiliations: ['epic'],
    rating: 4.4,
    reviewCount: 1523,
    heroImage: 'https://images.unsplash.com/photo-1486444786609-e3c8dcb0958e?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1486444786609-e3c8dcb0958e?w=1200',
    weather: {
      current: {
        temp: 29,
        condition: 'Cloudy',
        windSpeed: 11,
        humidity: 62,
      },
      forecast: [
        { day: 'Mon', high: 33, low: 19, condition: 'Snowy', snowChance: 74 },
        { day: 'Tue', high: 31, low: 17, condition: 'Snowy', snowChance: 69 },
        { day: 'Wed', high: 28, low: 14, condition: 'Partly Cloudy', snowChance: 29 },
        { day: 'Thu', high: 34, low: 22, condition: 'Sunny', snowChance: 6 },
        { day: 'Fri', high: 38, low: 25, condition: 'Cloudy', snowChance: 26 },
        { day: 'Sat', high: 40, low: 27, condition: 'Snowy', snowChance: 66 },
        { day: 'Sun', high: 35, low: 21, condition: 'Partly Cloudy', snowChance: 47 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/keystoneresort',
      instagram: 'https://www.instagram.com/keystoneresort',
      youtube: 'https://www.youtube.com/@keystoneresort',
      tiktok: 'https://www.tiktok.com/@keystoneresort',
      x: 'https://twitter.com/keystoneresort',
    },
    features: {
      hasPark: true,
      hasHalfpipe: true,
      hasNightSkiing: true,
      hasBackcountryAccess: false,
      hasSpaVillage: false,
    },
    tags: ['epic-pass', 'night-skiing', 'family-friendly', 'large'],
  },
  {
    id: 'resort:telluride',
    slug: 'telluride',
    name: 'Telluride Ski Resort',
    tagline: 'The most beautiful place you\'ll ever ski',
    description: 'Dramatic San Juan Mountain setting with challenging terrain and stunning views.',
    location: { lat: 37.9375, lng: -107.8123 },
    nearestCity: 'Telluride, CO',
    distanceFromDenver: 330,
    driveTimeFromDenver: 390,
    stats: {
      skiableAcres: 2000,
      liftsCount: 18,
      runsCount: 148,
      verticalDrop: 4425,
      baseElevation: 8725,
      summitElevation: 13150,
      avgAnnualSnowfall: 309,
    },
    terrain: {
      beginner: 23,
      intermediate: 36,
      advanced: 41,
      expert: 0,
    },
    conditions: {
      snowfall24h: 11,
      snowfall72h: 19,
      baseDepth: 84,
      terrainOpen: 86,
      liftsOpen: 16,
      status: 'open',
    },
    passAffiliations: ['ikon'],
    rating: 4.9,
    reviewCount: 892,
    heroImage: 'https://images.unsplash.com/photo-1418290232843-5d7a0bd93f7d?w=800',
    trailMapUrl: 'https://images.unsplash.com/photo-1418290232843-5d7a0bd93f7d?w=1200',
    weather: {
      current: {
        temp: 21,
        condition: 'Sunny',
        windSpeed: 8,
        humidity: 58,
      },
      forecast: [
        { day: 'Mon', high: 26, low: 11, condition: 'Snowy', snowChance: 72 },
        { day: 'Tue', high: 24, low: 9, condition: 'Snowy', snowChance: 81 },
        { day: 'Wed', high: 20, low: 5, condition: 'Partly Cloudy', snowChance: 34 },
        { day: 'Thu', high: 27, low: 15, condition: 'Sunny', snowChance: 9 },
        { day: 'Fri', high: 31, low: 18, condition: 'Cloudy', snowChance: 33 },
        { day: 'Sat', high: 33, low: 20, condition: 'Snowy', snowChance: 77 },
        { day: 'Sun', high: 28, low: 14, condition: 'Partly Cloudy', snowChance: 44 },
      ],
    },
    socialMedia: {
      facebook: 'https://www.facebook.com/telluride',
      instagram: 'https://www.instagram.com/tellurideskiandgolf',
      youtube: 'https://www.youtube.com/@telluride',
      tiktok: 'https://www.tiktok.com/@tellurideskiandgolf',
      x: 'https://twitter.com/tellurideski',
    },
    features: {
      hasPark: true,
      hasHalfpipe: false,
      hasNightSkiing: false,
      hasBackcountryAccess: true,
      hasSpaVillage: true,
    },
    tags: ['destination', 'ikon-pass', 'scenic', 'expert', 'large'],
  },
];
