import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const killington: Resort = {
  id: 'resort:killington',
  slug: 'killington',
  name: 'Killington Resort',
  tagline: 'The Beast of the East with the longest season',
  description: 'Killington Resort is the largest ski area in the eastern United States and has earned its nickname "The Beast of the East" through sheer scale and aggressive snowmaking. Spanning seven peaks and over 1,500 acres, Killington offers more terrain variety than any other eastern resort. The resort is famous for opening first and closing last on the East Coast, often extending the season from October through June. Killington\'s legendary nightlife along the Access Road is as famous as its skiing, making it a complete winter destination.',
  isActive: true,
  isLost: false,
  location: { lat: 43.6045, lng: -72.8201 },
  nearestCity: 'Killington, VT',
  distanceFromDenver: 1950,
  driveTimeFromDenver: 1800,
  stats: {
    skiableAcres: 1509,
    liftsCount: 22,
    runsCount: 155,
    verticalDrop: 3050,
    baseElevation: 1165,
    summitElevation: 4215,
    avgAnnualSnowfall: 250,
  },
  terrain: {
    beginner: 28,
    intermediate: 33,
    advanced: 21,
    expert: 18,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.4,
  reviewCount: 1567,
  heroImage: '/images/killington-hero.jpg',
  websiteUrl: 'https://www.killington.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/killingtonresort',
    instagram: 'https://www.instagram.com/killingtonmtn',
  },
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'beast-of-east', 'long-season', 'vermont', 'nightlife'],
  highSpeedLifts: {
    count: 7,
    items: [
      { name: 'K-1 Express Gondola', url: 'https://www.killington.com' },
      { name: 'Skye Peak Express', url: 'https://www.killington.com' },
      { name: 'Superstar Express', url: 'https://www.killington.com' },
      { name: 'Needles Eye Express', url: 'https://www.killington.com' },
      { name: 'Ramshead Express', url: 'https://www.killington.com' },
    ],
  },
};
