import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const madRiverGlen: Resort = {
  id: 'resort:mad-river-glen',
  slug: 'mad-river-glen',
  name: 'Mad River Glen',
  tagline: 'Ski It If You Can - America\'s most unique ski area',
  description: 'Mad River Glen is unlike any other ski area in North America. Owned cooperatively by its skiers since 1995, Mad River maintains its legendary "Ski It If You Can" attitude with no snowmaking on the upper mountain, no snowboarding allowed, and the only operating single chairlift in North America. The terrain is natural, challenging, and often icy, but dedicated skiers return for the ungroomed glades, legendary bump runs, and authentic atmosphere. The infamous Paradise double fall line is considered one of the most challenging trails in the East.',
  isActive: true,
  isLost: false,
  location: { lat: 44.2008, lng: -72.9217 },
  nearestCity: 'Waitsfield, VT',
  distanceFromDenver: 1980,
  driveTimeFromDenver: 1830,
  stats: {
    skiableAcres: 115,
    liftsCount: 5,
    runsCount: 53,
    verticalDrop: 2037,
    baseElevation: 1600,
    summitElevation: 3637,
    avgAnnualSnowfall: 250,
  },
  terrain: {
    beginner: 30,
    intermediate: 30,
    advanced: 23,
    expert: 17,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['indy'],
  rating: 4.7,
  reviewCount: 567,
  heroImage: '/images/mad-river-glen-hero.jpg',
  websiteUrl: 'https://www.madriverglen.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/MadRiverGlen',
    instagram: 'https://www.instagram.com/madriverglen',
  },
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['expert', 'indy-pass', 'ski-only', 'natural', 'vermont', 'cooperative'],
  highSpeedLifts: {
    count: 0,
    items: [],
  },
};
