import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const alpenglowArcticValley: Resort = {
  id: 'resort:alpenglow-arctic-valley',
  slug: 'alpenglow-arctic-valley',
  name: 'Alpenglow at Arctic Valley',
  tagline: 'Former military ski area in the Chugach Mountains',
  description: 'Alpenglow at Arctic Valley was an expansion of the Arctic Valley ski area that operated separately for a period before being consolidated. The area served both military personnel and civilians with additional terrain in the Chugach Mountains above Anchorage. Operations ceased as the military presence in the area changed and the separate operation was no longer viable.',
  isActive: false,
  isLost: true,
  location: { lat: 61.2500, lng: -149.5200 },
  nearestCity: 'Anchorage, AK',
  distanceFromDenver: 2750,
  driveTimeFromDenver: 2600,
  stats: {
    skiableAcres: 25,
    liftsCount: 1,
    runsCount: 6,
    verticalDrop: 600,
    baseElevation: 2600,
    summitElevation: 3200,
    avgAnnualSnowfall: 120,
  },
  terrain: {
    beginner: 30,
    intermediate: 40,
    advanced: 30,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 0,
  reviewCount: 0,
  heroImage: '/images/alpenglow-arctic-valley-hero.jpg',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['defunct', 'military', 'alaska', 'historic'],
};
