import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const altaSierra: Resort = {
  id: 'resort:alta-sierra',
  slug: 'alta-sierra',
  name: 'Alta Sierra',
  tagline: 'Intimate skiing in the Lake Isabella region',
  description: 'Alta Sierra is a small, community-focused ski area in the southern Sierra Nevada near Lake Isabella. The resort provides an accessible introduction to skiing for residents of the Central Valley and Southern California, with gentle terrain and affordable lift tickets. Alta Sierra operates seasonally based on snowfall conditions.',
  isActive: true,
  isLost: false,
  location: { lat: 35.7539, lng: -118.5553 },
  nearestCity: 'Wofford Heights, CA',
  distanceFromDenver: 800,
  driveTimeFromDenver: 740,
  stats: {
    skiableAcres: 50,
    liftsCount: 3,
    runsCount: 8,
    verticalDrop: 400,
    baseElevation: 7200,
    summitElevation: 7600,
    avgAnnualSnowfall: 60,
  },
  terrain: {
    beginner: 50,
    intermediate: 40,
    advanced: 10,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.5,
  reviewCount: 87,
  heroImage: '/images/alta-sierra-hero.jpg',
  websiteUrl: 'https://www.altasierra.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'small', 'beginner-friendly', 'southern-sierra', 'california', 'affordable'],
};
