import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const arapahoeBasin: Resort = {
  id: 'resort:arapahoe-basin',
  slug: 'arapahoe-basin',
  name: 'Arapahoe Basin',
  tagline: 'The Legend with the longest season in Colorado',
  description: 'Arapahoe Basin, affectionately known as "A-Basin" or "The Legend," is famous for its high-alpine terrain and the longest ski season in Colorado, often operating into June. Located on the Continental Divide at elevations reaching 13,050 feet, A-Basin offers above-treeline expert terrain including the Montezuma Bowl and the East Wall. The resort maintains a no-frills, local atmosphere that hardcore skiers treasure.',
  isActive: true,
  isLost: false,
  location: { lat: 39.6425, lng: -105.8719 },
  nearestCity: 'Keystone, CO',
  distanceFromDenver: 68,
  driveTimeFromDenver: 90,
  stats: {
    skiableAcres: 1428,
    liftsCount: 9,
    runsCount: 147,
    verticalDrop: 2530,
    baseElevation: 10520,
    summitElevation: 13050,
    avgAnnualSnowfall: 350,
  },
  terrain: {
    beginner: 10,
    intermediate: 30,
    advanced: 37,
    expert: 23,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.6,
  reviewCount: 1234,
  heroImage: '/images/arapahoe-basin-hero.jpg',
  websiteUrl: 'https://www.arapahoebasin.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'expert', 'high-alpine', 'colorado', 'long-season'],
};
