import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const arcticValley: Resort = {
  id: 'resort:arctic-valley',
  slug: 'arctic-valley',
  name: 'Arctic Valley',
  tagline: 'Military heritage skiing in the Chugach Mountains',
  description: 'Arctic Valley is a small ski area located in the Chugach Mountains northeast of Anchorage, originally developed for military personnel stationed at nearby bases. Now open to the public, Arctic Valley offers affordable skiing with genuine Alaska character and uncrowded slopes. The area features varied terrain including some surprisingly steep runs, all with spectacular views of the surrounding Chugach peaks and the Anchorage bowl below.',
  isActive: true,
  isLost: false,
  location: { lat: 61.2458, lng: -149.5308 },
  nearestCity: 'Anchorage, AK',
  distanceFromDenver: 2750,
  driveTimeFromDenver: 2600,
  stats: {
    skiableAcres: 40,
    liftsCount: 2,
    runsCount: 16,
    verticalDrop: 1000,
    baseElevation: 2500,
    summitElevation: 3500,
    avgAnnualSnowfall: 120,
  },
  terrain: {
    beginner: 25,
    intermediate: 50,
    advanced: 25,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 89,
  heroImage: '/images/arctic-valley-hero.jpg',
  websiteUrl: 'https://www.skiarctic.net',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['local', 'affordable', 'military', 'alaska', 'uncrowded'],
};
