import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const aspenHighlands: Resort = {
  id: 'resort:aspen-highlands',
  slug: 'aspen-highlands',
  name: 'Aspen Highlands',
  tagline: 'Locals\' favorite with legendary steeps and Highland Bowl',
  description: 'Aspen Highlands is the locals\' choice among Aspen\'s four mountains, renowned for its challenging terrain and the legendary Highland Bowl - a hike-to zone offering some of the most extreme inbounds terrain in North America. The mountain features consistent fall-line skiing, spectacular Maroon Bells views, and a more relaxed atmosphere than neighboring Aspen Mountain.',
  isActive: true,
  isLost: false,
  location: { lat: 39.1811, lng: -106.8556 },
  nearestCity: 'Aspen, CO',
  distanceFromDenver: 200,
  driveTimeFromDenver: 240,
  stats: {
    skiableAcres: 1040,
    liftsCount: 5,
    runsCount: 144,
    verticalDrop: 3635,
    baseElevation: 8040,
    summitElevation: 11675,
    avgAnnualSnowfall: 300,
  },
  terrain: {
    beginner: 18,
    intermediate: 30,
    advanced: 16,
    expert: 36,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.7,
  reviewCount: 892,
  heroImage: '/images/aspen-highlands-hero.jpg',
  websiteUrl: 'https://www.aspensnowmass.com/our-mountains/aspen-highlands',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'expert', 'highland-bowl', 'colorado', 'locals'],
};
