import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const badgerPass: Resort = {
  id: 'resort:badger-pass',
  slug: 'badger-pass',
  name: 'Badger Pass',
  tagline: 'California\'s first ski resort inside Yosemite National Park',
  description: 'Badger Pass Ski Area holds the distinction of being California\'s oldest ski area and the first resort in a national park. Located in Yosemite National Park, Badger Pass offers a unique skiing experience surrounded by the park\'s iconic scenery. The area focuses on families and beginners, with gentle terrain and an outstanding ski school. Cross-country skiing to Glacier Point is a highlight of any winter Yosemite visit.',
  isActive: true,
  isLost: false,
  location: { lat: 37.6628, lng: -119.6600 },
  nearestCity: 'Yosemite Valley, CA',
  distanceFromDenver: 820,
  driveTimeFromDenver: 760,
  stats: {
    skiableAcres: 90,
    liftsCount: 5,
    runsCount: 10,
    verticalDrop: 800,
    baseElevation: 7200,
    summitElevation: 8000,
    avgAnnualSnowfall: 220,
  },
  terrain: {
    beginner: 35,
    intermediate: 50,
    advanced: 15,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.1,
  reviewCount: 289,
  heroImage: '/images/badger-pass-hero.jpg',
  websiteUrl: 'https://www.travelyosemite.com/winter/badger-pass-ski-area',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'historic', 'national-park', 'yosemite', 'california', 'family'],
};
