import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const brighton: Resort = {
  id: 'resort:brighton',
  slug: 'brighton',
  name: 'Brighton Resort',
  tagline: 'Utah\'s favorite hometown mountain with night skiing',
  description: 'Brighton Resort is Utah\'s original ski destination and remains the beloved hometown mountain for Salt Lake City skiers. Located in Big Cottonwood Canyon, Brighton offers an unpretentious atmosphere, excellent terrain variety, and the only night skiing in the Cottonwood Canyons. The resort\'s 66 runs span from gentle beginner slopes to serious expert terrain, including the demanding Milly chutes and excellent tree skiing throughout. Brighton\'s affordable tickets and local vibe make it a perfect introduction to Utah skiing.',
  isActive: true,
  isLost: false,
  location: { lat: 40.5980, lng: -111.5831 },
  nearestCity: 'Salt Lake City, UT',
  distanceFromDenver: 535,
  driveTimeFromDenver: 465,
  stats: {
    skiableAcres: 1050,
    liftsCount: 7,
    runsCount: 66,
    verticalDrop: 1745,
    baseElevation: 8755,
    summitElevation: 10500,
    avgAnnualSnowfall: 500,
  },
  terrain: {
    beginner: 21,
    intermediate: 40,
    advanced: 39,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.4,
  reviewCount: 876,
  heroImage: '/images/brighton-hero.jpg',
  websiteUrl: 'https://www.brightonresort.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/BrightonResort',
    instagram: 'https://www.instagram.com/brightonresort',
  },
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: true,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['local', 'ikon-pass', 'night-skiing', 'affordable', 'utah', 'terrain-parks'],
  highSpeedLifts: {
    count: 4,
    items: [
      { name: 'Crest Express', url: 'https://www.brightonresort.com' },
      { name: 'Great Western Express', url: 'https://www.brightonresort.com' },
      { name: 'Milly Express', url: 'https://www.brightonresort.com' },
      { name: 'Snake Creek Express', url: 'https://www.brightonresort.com' },
    ],
  },
};
