import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const buttermilk: Resort = {
  id: 'resort:buttermilk',
  slug: 'buttermilk',
  name: 'Buttermilk Ski Area',
  tagline: 'Home of X Games and perfect for beginners',
  description: 'Buttermilk is Aspen\'s most beginner-friendly mountain and the annual home of the Winter X Games. The resort offers gentle terrain ideal for learning, combined with one of the world\'s best terrain parks that attracts elite freestyle athletes every January. Buttermilk provides a more relaxed, less crowded alternative to Aspen\'s other mountains.',
  isActive: true,
  isLost: false,
  location: { lat: 39.2069, lng: -106.8617 },
  nearestCity: 'Aspen, CO',
  distanceFromDenver: 200,
  driveTimeFromDenver: 240,
  stats: {
    skiableAcres: 470,
    liftsCount: 9,
    runsCount: 44,
    verticalDrop: 2030,
    baseElevation: 7870,
    summitElevation: 9900,
    avgAnnualSnowfall: 200,
  },
  terrain: {
    beginner: 35,
    intermediate: 39,
    advanced: 26,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.3,
  reviewCount: 567,
  heroImage: '/images/buttermilk-hero.jpg',
  websiteUrl: 'https://www.aspensnowmass.com/our-mountains/buttermilk',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'beginner-friendly', 'x-games', 'colorado', 'terrain-parks'],
};
