import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const clearySummit: Resort = {
  id: 'resort:cleary-summit',
  slug: 'cleary-summit',
  name: 'Cleary Summit',
  tagline: 'Historic Interior Alaska ski area on the Steese Highway',
  description: 'Cleary Summit was a ski area located along the Steese Highway northeast of Fairbanks. The area operated during the mid-20th century, providing skiing opportunities for Interior Alaska residents. The challenging access and harsh conditions eventually led to the closure of lift operations, though the area remains popular for backcountry skiing.',
  isActive: false,
  isLost: true,
  location: { lat: 65.0500, lng: -147.4000 },
  nearestCity: 'Fairbanks, AK',
  distanceFromDenver: 3080,
  driveTimeFromDenver: 2930,
  stats: {
    skiableAcres: 35,
    liftsCount: 1,
    runsCount: 8,
    verticalDrop: 500,
    baseElevation: 2200,
    summitElevation: 2700,
    avgAnnualSnowfall: 80,
  },
  terrain: {
    beginner: 20,
    intermediate: 50,
    advanced: 30,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 0,
  reviewCount: 0,
  heroImage: '/images/cleary-summit-hero.jpg',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['defunct', 'historic', 'alaska', 'backcountry'],
};
