import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const copperMountain: Resort = {
  id: 'resort:copper-mountain',
  slug: 'copper-mountain',
  name: 'Copper Mountain',
  tagline: 'Naturally divided terrain for every ability level',
  description: 'Copper Mountain is renowned for its naturally divided terrain, with beginner runs on the right, intermediate in the middle, and expert terrain on the left when facing the mountain. This unique layout makes navigation intuitive and keeps ability levels naturally separated. The resort offers exceptional value, excellent terrain parks, and an authentic Colorado atmosphere without the crowds of I-70\'s mega-resorts.',
  isActive: true,
  isLost: false,
  location: { lat: 39.5022, lng: -106.1497 },
  nearestCity: 'Frisco, CO',
  distanceFromDenver: 75,
  driveTimeFromDenver: 95,
  stats: {
    skiableAcres: 2490,
    liftsCount: 23,
    runsCount: 140,
    verticalDrop: 2738,
    baseElevation: 9712,
    summitElevation: 12313,
    avgAnnualSnowfall: 305,
  },
  terrain: {
    beginner: 21,
    intermediate: 25,
    advanced: 36,
    expert: 18,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.5,
  reviewCount: 1345,
  heroImage: '/images/copper-mountain-hero.jpg',
  websiteUrl: 'https://www.coppercolorado.com',
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['destination', 'ikon-pass', 'natural-terrain', 'value', 'colorado', 'terrain-parks'],
};
