import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const diamondPeak: Resort = {
  id: 'resort:diamond-peak',
  slug: 'diamond-peak',
  name: 'Diamond Peak',
  tagline: 'Incline Village\'s family-friendly gem with lake views',
  description: 'Diamond Peak in Incline Village offers an intimate, family-friendly skiing experience with stunning views of Lake Tahoe. Owned and operated by the Incline Village General Improvement District, the resort focuses on providing excellent value and a welcoming atmosphere for families and intermediates. The Child Ski Center is consistently rated among the best in the region.',
  isActive: true,
  isLost: false,
  location: { lat: 39.2539, lng: -119.9178 },
  nearestCity: 'Incline Village, NV',
  distanceFromDenver: 890,
  driveTimeFromDenver: 820,
  stats: {
    skiableAcres: 655,
    liftsCount: 7,
    runsCount: 31,
    verticalDrop: 1840,
    baseElevation: 6700,
    summitElevation: 8540,
    avgAnnualSnowfall: 325,
  },
  terrain: {
    beginner: 18,
    intermediate: 46,
    advanced: 36,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.3,
  reviewCount: 456,
  heroImage: '/images/diamond-peak-hero.jpg',
  websiteUrl: 'https://www.diamondpeak.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'family', 'views', 'lake-tahoe', 'nevada', 'affordable'],
};
