import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const granlibakken: Resort = {
  id: 'resort:granlibakken',
  slug: 'granlibakken',
  name: 'Granlibakken',
  tagline: 'Historic Tahoe ski hill perfect for young beginners',
  description: 'Granlibakken Tahoe is a small ski hill and historic resort in Tahoe City, focusing on young beginners and families. With just two surface lifts and gentle terrain, Granlibakken provides a perfect introduction to skiing in a low-pressure environment. The property includes a lodge and conference center with a rich history dating to the 1920s.',
  isActive: true,
  isLost: false,
  location: { lat: 39.1461, lng: -120.1650 },
  nearestCity: 'Tahoe City, CA',
  distanceFromDenver: 880,
  driveTimeFromDenver: 810,
  stats: {
    skiableAcres: 15,
    liftsCount: 2,
    runsCount: 5,
    verticalDrop: 300,
    baseElevation: 6300,
    summitElevation: 6600,
    avgAnnualSnowfall: 300,
  },
  terrain: {
    beginner: 90,
    intermediate: 10,
    advanced: 0,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 4.0,
  reviewCount: 156,
  heroImage: '/images/granlibakken-hero.jpg',
  websiteUrl: 'https://www.granlibakken.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['regional', 'historic', 'beginner-friendly', 'learn-to-ski', 'california', 'family'],
};
