import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const homewood: Resort = {
  id: 'resort:homewood',
  slug: 'homewood',
  name: 'Homewood Mountain Resort',
  tagline: 'Stunning Lake Tahoe views from every run',
  description: 'Homewood Mountain Resort offers perhaps the best views of Lake Tahoe from any ski resort, with the brilliant blue lake visible from nearly every run on the mountain. Located on Tahoe\'s west shore, Homewood provides a local, uncrowded experience with diverse terrain spread across two distinct areas. The resort has announced major redevelopment plans that will transform it while preserving its cherished character.',
  isActive: true,
  isLost: false,
  location: { lat: 39.0853, lng: -120.1614 },
  nearestCity: 'Homewood, CA',
  distanceFromDenver: 885,
  driveTimeFromDenver: 815,
  stats: {
    skiableAcres: 1260,
    liftsCount: 8,
    runsCount: 67,
    verticalDrop: 1650,
    baseElevation: 6230,
    summitElevation: 7880,
    avgAnnualSnowfall: 450,
  },
  terrain: {
    beginner: 15,
    intermediate: 50,
    advanced: 35,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.4,
  reviewCount: 478,
  heroImage: '/images/homewood-hero.jpg',
  websiteUrl: 'https://www.skihomewood.com',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'ikon-pass', 'views', 'lake-tahoe', 'california', 'uncrowded'],
};
