import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const mtBaldy: Resort = {
  id: 'resort:mt-baldy',
  slug: 'mt-baldy',
  name: 'Mt. Baldy',
  tagline: 'Old-school skiing on Southern California\'s highest peak',
  description: 'Mt. Baldy Ski Lifts is the oldest ski area in Southern California, located on the slopes of Mount San Antonio (locally known as Mt. Baldy), the highest peak in Los Angeles County. This no-frills operation offers a throwback skiing experience with vintage chairlifts, expert terrain, and spectacular views of the LA basin. Mt. Baldy attracts dedicated locals who appreciate its challenging runs and authentic character.',
  isActive: true,
  isLost: false,
  location: { lat: 34.2475, lng: -117.6453 },
  nearestCity: 'Mt. Baldy, CA',
  distanceFromDenver: 770,
  driveTimeFromDenver: 710,
  stats: {
    skiableAcres: 195,
    liftsCount: 4,
    runsCount: 26,
    verticalDrop: 2100,
    baseElevation: 6500,
    summitElevation: 8600,
    avgAnnualSnowfall: 140,
  },
  terrain: {
    beginner: 20,
    intermediate: 40,
    advanced: 30,
    expert: 10,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.8,
  reviewCount: 234,
  heroImage: '/images/mt-baldy-hero.jpg',
  websiteUrl: 'https://www.mtbaldyresort.com',
  features: {
    hasPark: false,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: false,
  },
  tags: ['regional', 'historic', 'expert', 'socal', 'california', 'old-school'],
};
