import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const parkCity: Resort = {
  id: 'resort:park-city',
  slug: 'park-city',
  name: 'Park City Mountain Resort',
  tagline: 'America\'s largest ski resort with Olympic heritage',
  description: 'Park City Mountain Resort is the largest ski resort in the United States, created by the 2015 merger of Park City Mountain Resort and Canyons Resort. Now interconnected via the Quicksilver Gondola, the combined resort offers over 7,300 acres of skiable terrain across an incredible variety of runs. The resort hosted multiple events during the 2002 Winter Olympics and maintains world-class terrain parks. Historic Main Street in Park City sits at the base, offering exceptional dining, shopping, and nightlife in a beautifully preserved mining town atmosphere.',
  isActive: true,
  isLost: false,
  location: { lat: 40.6514, lng: -111.5080 },
  nearestCity: 'Park City, UT',
  distanceFromDenver: 525,
  driveTimeFromDenver: 450,
  stats: {
    skiableAcres: 7300,
    liftsCount: 41,
    runsCount: 330,
    verticalDrop: 3226,
    baseElevation: 6900,
    summitElevation: 10026,
    avgAnnualSnowfall: 355,
  },
  terrain: {
    beginner: 8,
    intermediate: 42,
    advanced: 36,
    expert: 14,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['epic'],
  rating: 4.6,
  reviewCount: 2789,
  heroImage: '/images/park-city-hero.jpg',
  websiteUrl: 'https://www.parkcitymountain.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/parkcitymountain',
    instagram: 'https://www.instagram.com/parkcitymtn',
    youtube: 'https://www.youtube.com/parkcitymountain',
  },
  features: {
    hasPark: true,
    hasHalfpipe: true,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: true,
  },
  tags: ['destination', 'epic-pass', 'largest', 'olympic', 'utah', 'terrain-parks'],
  highSpeedLifts: {
    count: 16,
    items: [
      { name: 'Quicksilver Gondola', url: 'https://www.parkcitymountain.com' },
      { name: 'Orange Bubble Express', url: 'https://www.parkcitymountain.com' },
      { name: 'Red Pine Gondola', url: 'https://www.parkcitymountain.com' },
      { name: 'Flatiron Express', url: 'https://www.parkcitymountain.com' },
      { name: 'Dreamcatcher', url: 'https://www.parkcitymountain.com' },
    ],
  },
  baseAreas: {
    count: 3,
    items: [
      { name: 'Park City Base', url: 'https://www.parkcitymountain.com' },
      { name: 'Canyons Village', url: 'https://www.parkcitymountain.com' },
      { name: 'Historic Main Street', url: 'https://www.visitparkcity.com' },
    ],
  },
};
