import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const skiland: Resort = {
  id: 'resort:skiland',
  slug: 'skiland',
  name: 'Skiland',
  tagline: 'Interior Alaska skiing near Fairbanks',
  description: 'Skiland is the primary downhill ski area serving Fairbanks and Interior Alaska. Located in the hills north of Fairbanks, Skiland offers a full ski area experience despite the extreme northern latitude. The area features varied terrain, night skiing under the aurora borealis, and a genuine Alaska community atmosphere. Skiland operates in some of the coldest conditions of any ski area in North America.',
  isActive: true,
  isLost: false,
  location: { lat: 64.9033, lng: -147.5119 },
  nearestCity: 'Fairbanks, AK',
  distanceFromDenver: 3050,
  driveTimeFromDenver: 2900,
  stats: {
    skiableAcres: 80,
    liftsCount: 3,
    runsCount: 22,
    verticalDrop: 600,
    baseElevation: 1100,
    summitElevation: 1700,
    avgAnnualSnowfall: 70,
  },
  terrain: {
    beginner: 30,
    intermediate: 40,
    advanced: 30,
    expert: 0,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['local'],
  rating: 3.9,
  reviewCount: 78,
  heroImage: '/images/skiland-hero.jpg',
  websiteUrl: 'https://www.skiland.org',
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: true,
    hasBackcountryAccess: false,
    hasSpaVillage: false,
  },
  tags: ['local', 'northern', 'night-skiing', 'alaska', 'aurora'],
};
