import { Resort } from '../../../apps/v1/lib/mock-data/types';

export const sugarBowl: Resort = {
  id: 'resort:sugar-bowl',
  slug: 'sugar-bowl',
  name: 'Sugar Bowl Resort',
  tagline: 'Historic Lake Tahoe skiing with European charm',
  description: 'Sugar Bowl Resort is one of Lake Tahoe\'s most historic ski areas, founded in 1939 with backing from Walt Disney and designed to bring European alpine skiing to California. The resort spans four peaks and captures massive amounts of Sierra snow due to its location at the crest of Donner Summit. Sugar Bowl maintains its exclusive, members-oriented atmosphere while welcoming the public to some of the best powder skiing at Tahoe. The iconic gondola connects the historic Village with the slopes, and the resort\'s Royal Gorge provides unparalleled cross-country skiing access.',
  isActive: true,
  isLost: false,
  location: { lat: 39.3044, lng: -120.3339 },
  nearestCity: 'Norden, CA',
  distanceFromDenver: 860,
  driveTimeFromDenver: 790,
  stats: {
    skiableAcres: 1650,
    liftsCount: 13,
    runsCount: 103,
    verticalDrop: 1500,
    baseElevation: 6883,
    summitElevation: 8383,
    avgAnnualSnowfall: 500,
  },
  terrain: {
    beginner: 17,
    intermediate: 45,
    advanced: 25,
    expert: 13,
  },
  conditions: {
    snowfall24h: 0,
    snowfall72h: 0,
    baseDepth: 0,
    terrainOpen: 0,
    liftsOpen: 0,
    status: 'closed',
  },
  passAffiliations: ['ikon'],
  rating: 4.5,
  reviewCount: 678,
  heroImage: '/images/sugar-bowl-hero.jpg',
  websiteUrl: 'https://www.sugarbowl.com',
  socialMedia: {
    facebook: 'https://www.facebook.com/sugarbowlresort',
    instagram: 'https://www.instagram.com/sugarbowlresort',
  },
  features: {
    hasPark: true,
    hasHalfpipe: false,
    hasNightSkiing: false,
    hasBackcountryAccess: true,
    hasSpaVillage: true,
  },
  tags: ['historic', 'ikon-pass', 'deep-snow', 'lake-tahoe', 'california', 'european'],
  highSpeedLifts: {
    count: 5,
    items: [
      { name: 'Magic Carpet Gondola', url: 'https://www.sugarbowl.com' },
      { name: 'Mount Judah Express', url: 'https://www.sugarbowl.com' },
      { name: 'Crow\'s Nest Express', url: 'https://www.sugarbowl.com' },
      { name: 'Christmas Tree Express', url: 'https://www.sugarbowl.com' },
    ],
  },
};
